/*global systemDictionary:true */
"use strict";

// @ts-ignore
systemDictionary = {
    "Monitoring of devices based on consumption": {
        "en": "Monitoring of devices based on consumption",
        "de": "Überwachung von Geräten anhand des Verbrauchs",
        "ru": "Мониторинг устройств на основе потребления",
        "pt": "Monitoramento de dispositivos com base no consumo",
        "nl": "Toezicht op apparaten op basis van verbruik",
        "fr": "Suivi des appareils en fonction de la consommation",
        "it": "Monitoraggio dei dispositivi in base ai consumi",
        "es": "Monitorización de dispositivos en función del consumo",
        "pl": "Monitoring urządzeń na podstawie zużycia",
        "zh-cn": "基于消耗的设备监控"
      },
    "Configuration": {
        "en": "Configuration",
        "de": "Konfiguration",
        "ru": "Конфигурация",
        "pt": "Configuração",
        "nl": "Configuratie",
        "fr": "Configuration",
        "it": "Configurazione",
        "es": "Configuración",
        "pl": "Konfiguracja",
        "zh-cn": "配置"
    },
    "active": {
        "en": "active",
        "de": "aktiv",
        "ru": "активный",
        "pt": "ativo",
        "nl": "actief",
        "fr": "actif",
        "it": "attivo",
        "es": "activo",
        "pl": "aktywny",
        "zh-cn": "积极的"
    },
    "device": {
        "en": "device",
        "de": "Gerät",
        "ru": "устройство",
        "pt": "dispositivo",
        "nl": "apparaat",
        "fr": "appareil",
        "it": "dispositivo",
        "es": "dispositivo",
        "pl": "urządzenie",
        "zh-cn": "设备"
    },
    "switch off": {
        "en": "switch off",
        "de": "ausschalten",
        "ru": "выключить",
        "pt": "desligar",
        "nl": "Uitzetten",
        "fr": "éteindre",
        "it": "spegnere",
        "es": "apagar",
        "pl": "wyłączyć",
        "zh-cn": "关掉"
    },
    "switch off after minutes": {
        "en": "switch off after minutes",
        "de": "Abschalten nach Minuten",
        "ru": "выключить через несколько минут",
        "pt": "desligue após minutos",
        "nl": "na minuten uitschakelen",
        "fr": "s'éteint après quelques minutes",
        "it": "si spegne dopo pochi minuti",
        "es": "apagar después de minutos",
        "pl": "wyłącz po minutach",
        "zh-cn": "几分钟后关闭"
    },
    "abort detection": {
        "en": "abort detection",
        "de": "Abbrucherkennung",
        "ru": "прервать обнаружение",
        "pt": "detecção de aborto",
        "nl": "detectie afbreken",
        "fr": "abandonner la détection",
        "it": "interruzione del rilevamento",
        "es": "abortar la detección",
        "pl": "przerwać wykrywanie",
        "zh-cn": "中止检测"
    },
    "devices": {
        "en": "devices",
        "de": "Geräte",
        "ru": "устройства",
        "pt": "dispositivos",
        "nl": "apparaten",
        "fr": "dispositifs",
        "it": "dispositivi",
        "es": "dispositivos",
        "pl": "urządzenia",
        "zh-cn": "设备"
    },
    "add device": {
        "en": "add device",
        "de": "Gerät hinzufügen",
        "ru": "добавить устройство",
        "pt": "Adicionar Dispositivo",
        "nl": "Voeg toestel toe",
        "fr": "ajouter un appareil",
        "it": "Aggiungi dispositivo",
        "es": "añadir dispositivo",
        "pl": "Dodaj urządzenie",
        "zh-cn": "添加设备"
    },
    "Input checked": {
        "en": "Input checked",
        "de": "Eingabe überprüft",
        "ru": "Ввод проверен",
        "pt": "Entrada verificada",
        "nl": "Invoer aangevinkt",
        "fr": "Entrée cochée",
        "it": "Input controllato",
        "es": "Entrada marcada",
        "pl": "Wejście sprawdzone",
        "zh-cn": "输入检查"
    },
    "help": {
        "en": "help",
        "de": "Hilfe",
        "ru": "помощь",
        "pt": "ajuda",
        "nl": "helpen",
        "fr": "aider",
        "it": "aiuto",
        "es": "ayudar",
        "pl": "Wsparcie",
        "zh-cn": "帮助"
    },
    "*Required fields": {
        "en": "*Required fields",
        "de": "*Felder erforderlich",
        "ru": "*Обязательные поля",
        "pt": "*Os campos obrigatórios",
        "nl": "*Verplichte velden",
        "fr": "*Champs obligatoires",
        "it": "*Campi richiesti",
        "es": "*Campos requeridos",
        "pl": "*Wymagane pola",
        "zh-cn": "*必填字段"
    },
    "device name": {
        "en": "device name",
        "de": "Gerätename",
        "ru": "имя устройства",
        "pt": "nome do dispositivo",
        "nl": "toestelnaam",
        "fr": "nom de l'appareil",
        "it": "nome del dispositivo",
        "es": "nombre del dispositivo",
        "pl": "Nazwa urządzenia",
        "zh-cn": "设备名称"
    },
    "device type": {
        "en": "device type",
        "de": "Gerätetyp",
        "ru": "тип устройства",
        "pt": "tipo de dispositivo",
        "nl": "soort apparaat",
        "fr": "type d'appareil",
        "it": "tipo di dispositivo",
        "es": "tipo de dispositivo",
        "pl": "rodzaj urządzenia",
        "zh-cn": "设备类型",
    },
    "consumption": {
        "en": "consumption",
        "de": "Verbrauch",
        "ru": "потребление",
        "pt": "consumo",
        "nl": "consumptie",
        "fr": "consommation",
        "it": "consumo",
        "es": "consumo",
        "pl": "konsumpcja",
        "zh-cn": "消耗"
    },
    "Power switch": {
        "en": "Power switch",
        "de": "Stromschalter",
        "ru": "Выключатель",
        "pt": "Interruptor de energia",
        "nl": "Aan/uit-schakelaar:",
        "fr": "Interrupteur",
        "it": "Interruttore di alimentazione",
        "es": "Interruptor de alimentación",
        "pl": "Włącznik zasilania",
        "zh-cn": "开关;电源开关"
    },
    "starttext": {
        "en": "starttext",
        "de": "Starttext",
        "ru": "стартовый текст",
        "pt": "texto inicial",
        "nl": "starttekst",
        "fr": "texte de début",
        "it": "testo iniziale",
        "es": "texto de inicio",
        "pl": "tekst startowy",
        "zh-cn": "开始文本"
    },
    "endtext": {
        "en": "endtext",
        "de": "Endtext",
        "ru": "конечный текст",
        "pt": "texto final",
        "nl": "eindtekst",
        "fr": "texte de fin",
        "it": "testo finale",
        "es": "texto final",
        "pl": "tekst końcowy",
        "zh-cn": "正文"
    },
    "delete": {
        "en": "delete",
        "de": "löschen",
        "ru": "удалять",
        "pt": "excluir",
        "nl": "verwijderen",
        "fr": "effacer",
        "it": "eliminare",
        "es": "Eliminar",
        "pl": "usunąć",
        "zh-cn": "删除"
    },
    "Pls check input": {
        "en": "Pls check input",
        "de": "Bitte überprüfen Sie die Eingabe",
        "ru": "Пожалуйста, проверьте ввод",
        "pt": "Por favor, verifique a entrada",
        "nl": "Pls check input",
        "fr": "Veuillez vérifier l'entrée",
        "it": "Si prega di controllare l'input",
        "es": "Por favor verifique la entrada",
        "pl": "Pls sprawdź wejście!",
        "zh-cn": "请检查输入"
    },
    "invalid input detected": {
        "en": "invalid input detected",
        "de": "Ungültige Eingabe erkannt",
        "ru": "обнаружен неверный ввод",
        "pt": "entrada inválida detectada",
        "nl": "ongeldige invoer gedetecteerd",
        "fr": "entrée invalide détectée",
        "it": "è stato rilevato un input non valido",
        "es": "entrada no válida detectada",
        "pl": "wykryto nieprawidłowe dane wejściowe",
        "zh-cn": "检测到无效输入"
    },
    "add alexa": {
        "en": "add alexa",
        "de": "alexa hinzufügen",
        "ru": "добавить алекса",
        "pt": "adicionar alexa",
        "nl": "alexa toevoegen",
        "fr": "ajouter alexa",
        "it": "aggiungi alexa",
        "es": "agregar alexa",
        "pl": "dodaj Alexa",
        "zh-cn": "添加亚历克萨"
    },
    "*volume 0-100": {
        "en": "*volume 0-100",
        "de": "*Lautstärke 0-100",
        "ru": "*громкость 0-100",
        "pt": "*volume 0-100",
        "nl": "*volume 0-100",
        "fr": "*volume 0-100",
        "it": "*volume 0-100",
        "es": "*volumen 0-100",
        "pl": "*objętość 0-100",
        "zh-cn": "*音量 0-100"
    },
    "active from hour": {
        "en": "active from hour",
        "de": "aktiv: Stunde",
        "ru": "активен с часа",
        "pt": "ativo da hora",
        "nl": "actief vanaf uur",
        "fr": "actif à partir de l'heure",
        "it": "attivo da ora",
        "es": "activo desde la hora",
        "pl": "aktywny od godziny",
        "zh-cn": "从小时活跃"
    },
    "active from minute": {
        "en": "active from minute",
        "de": "aktiv: Minute",
        "ru": "активен с минуты",
        "pt": "ativo a partir do minuto",
        "nl": "actief vanaf minuut",
        "fr": "actif à partir de la minute",
        "it": "attivo dal minuto",
        "es": "activo desde el minuto",
        "pl": "aktywny od minuty",
        "zh-cn": "从一分钟开始活跃"
    },
    "inactive from hour": {
        "en": "inactive from hour",
        "de": "inaktiv: Stunde",
        "ru": "неактивен с часа",
        "pt": "inativo da hora",
        "nl": "inactief vanaf uur",
        "fr": "inactif depuis heure",
        "it": "inattivo da ora",
        "es": "inactivo desde la hora",
        "pl": "nieaktywny od godziny",
        "zh-cn": "从小时不活动"
    },
    "inactive from minute": {
        "en": "inactive from minute",
        "de": "inaktiv: minute",
        "ru": "неактивен с минуты",
        "pt": "inativo a partir do minuto",
        "nl": "inactief vanaf minuut",
        "fr": "inactif depuis une minute",
        "it": "inattivo da minuto",
        "es": "inactivo desde el minuto",
        "pl": "nieaktywny od minuty",
        "zh-cn": "从一分钟起不活跃"
    },
    "add sayit device": {
        "en": "add sayit device",
        "de": "Sayit-Gerät hinzufügen",
        "ru": "добавить сайит устройство",
        "pt": "adicionar dispositivo sayit",
        "nl": "voeg Sayit-apparaat toe",
        "fr": "ajouter un appareil sayit",
        "it": "aggiungi dispositivo Sayit",
        "es": "añadir dispositivo sayit",
        "pl": "dodaj urządzenie sayit",
        "zh-cn": "添加sayit设备"
    },
    "no entries found": {
        "en": "no entries found",
        "de": "Keine Einträge gefunden",
        "ru": "записей не найдено",
        "pt": "nenhuma entrada encontrada",
        "nl": "geen inzendingen gevonden",
        "fr": "aucune entrée trouvée",
        "it": "nessuna voce trovata",
        "es": "entradas no encontradas",
        "pl": "nie znaleziono wpisów",
        "zh-cn": "未找到条目"
    },
    "add whatsapp user": {
        "en": "add whatsapp user",
        "de": "WhatsApp-Benutzer hinzufügen",
        "ru": "добавить пользователя ватсап",
        "pt": "adicionar usuário whatsapp",
        "nl": "WhatsApp-gebruiker toevoegen",
        "fr": "ajouter un utilisateur WhatsApp",
        "it": "aggiungi utente whatsapp",
        "es": "añadir usuario de whatsapp",
        "pl": "dodaj użytkownika WhatsApp",
        "zh-cn": "添加whatsapp用户"
    },
    "add pushover instance": {
        "en": "add pushover instance",
        "de": "Pushover-Instanz hinzufügen",
        "ru": "добавить экземпляр pushover",
        "pt": "adicionar instância pushover",
        "nl": "pushover-instantie toevoegen",
        "fr": "ajouter une instance pushover",
        "it": "aggiungi un'istanza pushover",
        "es": "añadir instancia pushover",
        "pl": "dodaj instancję pushover",
        "zh-cn": "添加 pushover 实例"
    },
    "*pushover instance": {
        "en": "*pushover instance",
        "de": "*Pushover-Instanz",
        "ru": "* пуш-овер экземпляр",
        "pt": "*instância de pushover",
        "nl": "*pushover-instantie",
        "fr": "*instance de transfert",
        "it": "*istanza pushover",
        "es": "*instancia pushover",
        "pl": "*instancja pushover",
        "zh-cn": "*推送实例"
    },
    "*priority": {
        "en": "*priority",
        "de": "*Priorität",
        "ru": "* приоритет",
        "pt": "*prioridade",
        "nl": "*prioriteit",
        "fr": "*priorité",
        "it": "*priorità",
        "es": "*prioridad",
        "pl": "*priorytet",
        "zh-cn": "*优先事项"
    },
    "*sound": {
        "en": "*sound",
        "de": "*Klang",
        "ru": "*звук",
        "pt": "*som",
        "nl": "*geluid",
        "fr": "*son",
        "it": "*suono",
        "es": "*sonar",
        "pl": "*dźwięk",
        "zh-cn": "*声音"
    },
    "*name": {
        "en": "*name",
        "de": "*Name",
        "ru": "*название",
        "pt": "*nome",
        "nl": "*naam",
        "fr": "*Nom",
        "it": "*nome",
        "es": "*nombre",
        "pl": "*nazwać",
        "zh-cn": "*姓名"
    },
    "name": {
        "en": "name",
        "de": "Name",
        "ru": "название",
        "pt": "nome",
        "nl": "naam",
        "fr": "Nom",
        "it": "nome",
        "es": "nombre",
        "pl": "nazwać",
        "zh-cn": "姓名"
    },
    "add email": {
        "en": "add email",
        "de": "E-Mail hinzufügen",
        "ru": "добавить электронную почту",
        "pt": "adicionar e-mail",
        "nl": "e-mail toevoegen",
        "fr": "ajouter un e-mail",
        "it": "aggiungi e-mail",
        "es": "añadir correo electrónico",
        "pl": "dodaj e-mail",
        "zh-cn": "添加电子邮件"
    },
    "*sender address": {
        "en": "*sender address",
        "de": "*Absenderadresse",
        "ru": "*адрес отправителя",
        "pt": "*Endereço do remetente",
        "nl": "*Zender adres",
        "fr": "*adresse de l'expéditeur",
        "it": "*indirizzo del mittente",
        "es": "*dirección del remitente",
        "pl": "*adres nadawcy",
        "zh-cn": "*发件人地址"
    },
    "*receiver address": {
        "en": "*receiver address",
        "de": "*Empfängeradresse",
        "ru": "*адрес получателя",
        "pt": "*endereço do destinatário",
        "nl": "*ontvanger adres",
        "fr": "*adresse du destinataire",
        "it": "*indirizzo del destinatario",
        "es": "*dirección del destinatario",
        "pl": "*Odbiorca adres",
        "zh-cn": "*收件人地址"
    },
    "default type config": {
        "en": "default type config",
        "de": "Gerätewerte Standard",
        "ru": "конфигурация типа по умолчанию",
        "pt": "configuração de tipo padrão",
        "nl": "standaard type configuratie",
        "fr": "configuration de type par défaut",
        "it": "tipo predefinito config",
        "es": "configuración de tipo predeterminada",
        "pl": "domyślna konfiguracja typu",
        "zh-cn": "默认类型配置"
    },
    "custom type config": {
        "en": "custom type config",
        "de": "Gerätewerte User",
        "ru": "конфигурация пользовательского типа",
        "pt": "configuração de tipo personalizado",
        "nl": "aangepast type configuratie",
        "fr": "configuration de type personnalisée",
        "it": "tipo personalizzato config",
        "es": "configuración de tipo personalizado",
        "pl": "konfiguracja typu niestandardowego",
        "zh-cn": "自定义类型配置"
    },
    "threshold 'start' (watt)": {
        "en": "threshold 'start' (watt)",
        "de": "Schwelle 'Start' (Watt)",
        "ru": "порог «старт» (ватт)",
        "pt": "limite 'iniciar' (watt)",
        "nl": "drempel 'start' (watt)",
        "fr": "seuil 'start' (watt)",
        "it": "soglia 'start' (watt)",
        "es": "umbral 'inicio' (vatios)",
        "pl": "próg „start” (wat)",
        "zh-cn": "阈值“开始”（瓦特）"
      },
      "threshold 'end' (watt)": {
        "en": "threshold 'end' (watt)",
        "de": "Schwelle 'Ende' (Watt)",
        "ru": "порог «конец» (ватт)",
        "pt": "limite 'fim' (watt)",
        "nl": "drempel 'eind' (watt)",
        "fr": "seuil 'fin' (watt)",
        "it": "soglia 'fine' (watt)",
        "es": "umbral 'fin' (vatios)",
        "pl": "próg „koniec” (wat)",
        "zh-cn": "阈值“结束”（瓦特）"
      },
      "threshold 'standby' (watt)": {
        "en": "threshold 'standby' (watt)",
        "de": "Schwelle 'Standby' (Watt)",
        "ru": "порог «ожидания» (ватт)",
        "pt": "limiar 'standby' (watt)",
        "nl": "drempel 'standby' (watt)",
        "fr": "seuil 'veille' (watt)",
        "it": "soglia 'standby' (watt)",
        "es": "umbral 'en espera' (vatios)",
        "pl": "próg czuwania (wat)",
        "zh-cn": "阈值“待机”（瓦特）"
      },
      "number of 'start' values": {
        "en": "number of 'start' values",
        "de": "Anzahl der 'Start'-Werte",
        "ru": "количество «начальных» значений",
        "pt": "número de valores 'iniciais'",
        "nl": "aantal 'start'-waarden",
        "fr": "nombre de valeurs 'début'",
        "it": "numero di valori 'iniziali'",
        "es": "número de valores de 'inicio'",
        "pl": "liczba wartości „początkowych”",
        "zh-cn": "“开始”值的数量"
      },
      "number of ​'end' values": {
        "en": "number of ​'end' values",
        "de": "Anzahl der ​'End'-Werte",
        "ru": "количество «конечных» значений",
        "pt": "número de valores 'final'",
        "nl": "aantal ​'eind'-waarden",
        "fr": "nombre de valeurs \"fin\"",
        "it": "numero di \"valori finali\".",
        "es": "número de valores 'finales'",
        "pl": "liczba ​wartości końcowych",
        "zh-cn": "“结束”值的数量"
      },
      "device status": {
        "en": "device status",
        "de": "Gerätestatus",
        "ru": "состояние устройства",
        "pt": "status do dispositivo",
        "nl": "Apparaatstatus",
        "fr": "statut du périphérique",
        "it": "stato del dispositivo",
        "es": "estado del dispositivo",
        "pl": "status urządzenia",
        "zh-cn": "设备状态"
      },
      "status: 'in action'": {
        "en": "status: 'in action'",
        "de": "Status: 'in Aktion'",
        "ru": "статус: \"в действии\"",
        "pt": "estado: 'em ação'",
        "nl": "status: 'in actie'",
        "fr": "statut : 'en action'",
        "it": "stato: 'in azione'",
        "es": "estado: 'en acción'",
        "pl": "status: „w akcji”",
        "zh-cn": "状态：'在行动'"
      },
      "status: 'standby'": {
        "en": "status: 'standby'",
        "de": "Status: 'Standby'",
        "ru": "статус: «ожидание»",
        "pt": "estado: 'em espera'",
        "nl": "status: 'stand-by'",
        "fr": "état : 'en attente'",
        "it": "stato: 'standby'",
        "es": "estado: 'en espera'",
        "pl": "status: „gotowość”",
        "zh-cn": "状态：“待命”"
      },
      "status: 'device off'": {
        "en": "status: 'device off'",
        "de": "Status: 'Gerät aus'",
        "ru": "статус: \"устройство выключено\"",
        "pt": "status: 'dispositivo desligado'",
        "nl": "status: 'apparaat uit'",
        "fr": "statut : \"appareil éteint\"",
        "it": "stato: 'dispositivo spento'",
        "es": "estado: 'dispositivo apagado'",
        "pl": "status: „urządzenie wyłączone”",
        "zh-cn": "状态：“设备关闭”"
      }



};