/*global systemDictionary:true */
"use strict";

// @ts-ignore
systemDictionary = {
    "device-reminder adapter settings": {
        "en": "Adapter settings for device-reminder",
        "de": "Adaptereinstellungen für device-reminder",
        "ru": "Настройки адаптера для device-reminder",
        "pt": "Configurações do adaptador para device-reminder",
        "nl": "Adapterinstellingen voor device-reminder",
        "fr": "Paramètres d'adaptateur pour device-reminder",
        "it": "Impostazioni dell'adattatore per device-reminder",
        "es": "Ajustes del adaptador para device-reminder",
        "pl": "Ustawienia adaptera dla device-reminder",
        "zh-cn": "device-reminder的适配器设置"
    },
    "Config": {
        "en": "Config",
        "de": "Konfiguration",
        "ru": "Конфиг",
        "pt": "Config",
        "nl": "Config",
        "fr": "Config",
        "it": "Config",
        "es": "Config",
        "pl": "Config",
        "zh-cn": "设定档"
      },
    "active": {
        "en": "active",
        "de": "aktiv",
        "ru": "активный",
        "pt": "ativo",
        "nl": "actief",
        "fr": "actif",
        "it": "attivo",
        "es": "activo",
        "pl": "aktywny",
        "zh-cn": "积极的"
    },
    "device": {
        "en": "device",
        "de": "Gerät",
        "ru": "устройство",
        "pt": "dispositivo",
        "nl": "apparaat",
        "fr": "appareil",
        "it": "dispositivo",
        "es": "dispositivo",
        "pl": "urządzenie",
        "zh-cn": "设备"
      },
      "alexa": {
        "en": "alexa",
        "de": "alexa",
        "ru": "Алекса",
        "pt": "alexa",
        "nl": "Alexa",
        "fr": "alexa",
        "it": "alexa",
        "es": "alexa",
        "pl": "alexa",
        "zh-cn": "亚历克斯"
      },
      "whatsapp": {
        "en": "whatsapp",
        "de": "WhatsApp",
        "ru": "WhatsApp",
        "pt": "Whatsapp",
        "nl": "whatsapp",
        "fr": "WhatsApp",
        "it": "WhatsApp",
        "es": "whatsapp",
        "pl": "WhatsApp",
        "zh-cn": "Whatsapp的"
      },
      "switch off": {
        "en": "switch off",
        "de": "ausschalten",
        "ru": "выключить",
        "pt": "desligar",
        "nl": "Uitzetten",
        "fr": "éteindre",
        "it": "spegnere",
        "es": "apagar",
        "pl": "wyłączyć",
        "zh-cn": "关掉"
      },
      "switch off after minutes": {
        "en": "switch off after minutes",
        "de": "Ausschalt-<br>verzögerung",
        "ru": "выключить<br>через<br>несколько<br>минут",
        "pt": "desligue<br>após<br>minutos",
        "nl": "uitschakelen<br>na minuten",
        "fr": "éteindre après<br>quelques minutes",
        "it": "spegnere dopo<br>minuti",
        "es": "apagar<br>después<br>de minutos",
        "pl": "wyłączyć<br>po minutach",
        "zh-cn": "几分钟后关闭"
      },
      "abort detection": {
        "en": "abort detection",
        "de": "Abbruch-<br>erkennung",
        "ru": "прервать<br>обнаружение",
        "pt": "detecção<br>de aborto",
        "nl": "de detectie<br>afbreken",
        "fr": "détection<br>d'abandon",
        "it": "interruzione<br>del<br>rilevamento",
        "es": "abortar la<br>detección",
        "pl": "przerwać<br>wykrywanie",
        "zh-cn": "中止检测"
      },

      "add device": {
        "en": "add device",
        "de": "Gerät hinzufügen",
        "ru": "добавить устройство",
        "pt": "Adicionar Dispositivo",
        "nl": "Voeg toestel toe",
        "fr": "ajouter un appareil",
        "it": "Aggiungi dispositivo",
        "es": "añadir dispositivo",
        "pl": "Dodaj urządzenie",
        "zh-cn": "添加设备"
      },
      "Input checked": {
        "en": "Input checked",
        "de": "Eingabe geprüft",
        "ru": "Ввод проверен",
        "pt": "Entrada verificada",
        "nl": "Input aangevinkt",
        "fr": "Entrée vérifiée",
        "it": "Input verificato",
        "es": "Entrada marcada",
        "pl": "Wejście sprawdzone",
        "zh-cn": "输入已检查"
      },
      "Required fields": {
        "en": "*Required fields",
        "de": "*Benötigte Felder",
        "ru": "* Обязательные поля",
        "pt": "*Os campos obrigatórios",
        "nl": "*Verplichte velden",
        "fr": "*Champs obligatoires",
        "it": "*Campi richiesti",
        "es": "*Campos requeridos",
        "pl": "*Wymagane pola",
        "zh-cn": "*必填项"
      },
      "close": {
        "en": "close",
        "de": "schließen",
        "ru": "Закрыть",
        "pt": "perto",
        "nl": "dichtbij",
        "fr": "Fermer",
        "it": "vicino",
        "es": "cerca",
        "pl": "blisko",
        "zh-cn": "关闭"
      },
      "save": {
        "en": "save",
        "de": "speichern",
        "ru": "спасти",
        "pt": "Salve ",
        "nl": "sparen",
        "fr": "sauvegarder",
        "it": "Salva",
        "es": "ahorrar",
        "pl": "zapisać",
        "zh-cn": "保存"
      },
      "Click here to edit %s": {
        "en": "Click here to edit %s",
        "de": "Klicken Sie hier, um %s  zu bearbeiten",
        "ru": "Нажмите здесь, чтобы отредактировать %s ",
        "pt": "Clique aqui para editar %s ",
        "nl": "Klik hier om %s  te bewerken",
        "fr": "Cliquez ici pour modifier %s ",
        "it": "Fare clic qui per modificare %s ",
        "es": "Haga clic aquí para editar %s ",
        "pl": "Kliknij tutaj, aby edytować %s ",
        "zh-cn": "点击此处编辑％s"
      },
      "Click here for create %s": {
        "en": "Click here for create %s",
        "de": "Klicken Sie hier, um %s zu erstellen",
        "ru": "Нажмите здесь, чтобы создать %s",
        "pt": "Clique aqui para criar %s",
        "nl": "Klik hier om %s  aan te maken",
        "fr": "Cliquez ici pour créer %s",
        "it": "Fare clic qui per creare %s",
        "es": "Haga clic aquí para crear %s",
        "pl": "Kliknij tutaj, aby utworzyć %s",
        "zh-cn": "单击此处创建％s"
      },
      "Error(s) found in configuration": {
        "en": "Error(s) found in configuration",
        "de": "Fehler in der Konfiguration gefunden",
        "ru": "В конфигурации обнаружены ошибки",
        "pt": "Erro (s) encontrado (s) na configuração",
        "nl": "Fout (en) gevonden in configuratie",
        "fr": "Erreur (s) trouvée (s) dans la configuration",
        "it": "Errori trovati nella configurazione",
        "es": "Error (s) encontrado en la configuración",
        "pl": "Znaleziono błędy w konfiguracji",
        "zh-cn": "配置中发现错误"
      },
      "Error(s) found in %s": {
        "en": "Error(s) found in %s",
        "de": "Fehler in %s gefunden",
        "ru": "Обнаружены ошибки в %s",
        "pt": "Erro (s) encontrado (s) em %s",
        "nl": "Fout (en) gevonden in %s",
        "fr": "Erreur (s) trouvée (s) dans %s",
        "it": "Errori trovati in %s",
        "es": "Error (s) encontrado en %s",
        "pl": "Znaleziono błędy w %s",
        "zh-cn": "％s中发现错误"
      },
      "invalid input detected": {
        "en": "invalid input detected",
        "de": "ungültige Eingabe erkannt",
        "ru": "обнаружен неверный ввод",
        "pt": "entrada inválida detectada",
        "nl": "ongeldige invoer gedetecteerd",
        "fr": "entrée non valide détectée",
        "it": "rilevato input non valido",
        "es": "entrada inválida detectada",
        "pl": "wykryto nieprawidłowe dane wejściowe",
        "zh-cn": "检测到无效输入"
      },
      "no entries found": {
        "en": "no entries found",
        "de": "Keine Einträge gefunden",
        "ru": "записей не найдено",
        "pt": "nenhuma entrada encontrada",
        "nl": "geen items gevonden",
        "fr": "aucune entrée trouvée",
        "it": "nessuna voce trovata",
        "es": "entradas no encontradas",
        "pl": "nie znaleziono wpisów",
        "zh-cn": "找不到条目"
      },
      "Pls check input": {
        "en": "Pls check input",
        "de": "Bitte überprüfen Sie die Eingabe",
        "ru": "Пожалуйста, проверьте ввод",
        "pt": "Por favor, verifique a entrada",
        "nl": "Controleer de invoer",
        "fr": "Veuillez vérifier l'entrée",
        "it": "Ingresso di controllo di Pls",
        "es": "Por favor, compruebe la entrada",
        "pl": "Pls sprawdź dane wejściowe",
        "zh-cn": "请检查输入"
      },
      "help": {
        "en": "help",
        "de": "Hilfe",
        "ru": "помощь",
        "pt": "ajuda",
        "nl": "helpen",
        "fr": "aider",
        "it": "Aiuto",
        "es": "ayuda",
        "pl": "Wsparcie",
        "zh-cn": "帮助"
      },
      "devices": {
        "en": "devices",
        "de": "Geräte",
        "ru": "устройства",
        "pt": "dispositivos",
        "nl": "apparaten",
        "fr": "dispositifs",
        "it": "dispositivi",
        "es": "dispositivos",
        "pl": "urządzenia",
        "zh-cn": "设备"
      },
      "device name": {
        "en": "*device name",
        "de": "*Gerätename",
        "ru": "*имя устройства",
        "pt": "*nome do dispositivo",
        "nl": "*toestelnaam",
        "fr": "*nom de l'appareil",
        "it": "*nome del dispositivo",
        "es": "*nombre del dispositivo",
        "pl": "*Nazwa urządzenia",
        "zh-cn": "*设备名称"
      },
      "device type": {
        "en": "*device type",
        "de": "*Gerätetyp",
        "ru": "*тип устройства",
        "pt": "*tipo de dispositivo",
        "nl": "*soort apparaat",
        "fr": "*type d'appareil",
        "it": "*tipo di dispositivo",
        "es": "*tipo de dispositivo",
        "pl": "*rodzaj urządzenia",
        "zh-cn": "*设备类型"
      },
      "consumption/energy": {
        "en": "*consumption/energy",
        "de": "*Verbrauch / Energie",
        "ru": "*потребление / энергия",
        "pt": "*consumo / energia",
        "nl": "*verbruik / energie",
        "fr": "*consommation / énergie",
        "it": "*consumo / energia",
        "es": "*consumo / energía",
        "pl": "*zużycie / energia",
        "zh-cn": "消耗/能源"
      },
      "Power switch": {
        "en": "Power switch",
        "de": "Schalter AN/AUS",
        "ru": "Выключатель",
        "pt": "Interruptor de energia",
        "nl": "Aan / uit-schakelaar",
        "fr": "Interrupteur",
        "it": "Interruttore di alimentazione",
        "es": "Interruptor de alimentación",
        "pl": "Włącznik zasilania",
        "zh-cn": "开关;电源开关"
      },
      "starttext": {
        "en": "starttext",
        "de": "Starttext",
        "ru": "starttext",
        "pt": "texto inicial",
        "nl": "starttekst",
        "fr": "texte de départ",
        "it": "starttext",
        "es": "starttext",
        "pl": "tekst startowy",
        "zh-cn": "起始文本"
      },
      "endtext": {
        "en": "endtext",
        "de": "Endtext",
        "ru": "конечный текст",
        "pt": "texto final",
        "nl": "endtext",
        "fr": "fin de texte",
        "it": "endtext",
        "es": "endtext",
        "pl": "tekst końcowy",
        "zh-cn": "结束语"
      },
      "delete": {
        "en": "delete",
        "de": "löschen",
        "ru": "Удалить",
        "pt": "excluir",
        "nl": "verwijderen",
        "fr": "effacer",
        "it": "Elimina",
        "es": "Eliminar",
        "pl": "kasować",
        "zh-cn": "删除"
      },

      "Configure your own device status": {
        "en": "Configure your own device status",
        "de": "Konfigurieren Sie Ihren eigenen Gerätestatus",
        "ru": "Настройте свой собственный статус устройства",
        "pt": "Configure o status do seu próprio dispositivo",
        "nl": "Configureer uw eigen apparaatstatus",
        "fr": "Configurez votre propre état de l'appareil",
        "it": "Configura lo stato del tuo dispositivo",
        "es": "Configure el estado de su propio dispositivo",
        "pl": "Skonfiguruj stan swojego urządzenia",
        "zh-cn": "配置您自己的设备状态"
      },
      "status: 'in action'": {
        "en": "status: 'in action'",
        "de": "Status: 'in Aktion'",
        "ru": "статус: «в действии»",
        "pt": "status: 'em ação'",
        "nl": "status: 'in actie'",
        "fr": "statut: 'en action'",
        "it": "stato: \"in azione\"",
        "es": "estado: 'en acción'",
        "pl": "status: „w akcji”",
        "zh-cn": "状态：“执行中”"
      },
      "custom devices": {
        "en": "custom devices",
        "de": "benutzerdefinierte Geräte",
        "ru": "кастомные устройства",
        "pt": "dispositivos personalizados",
        "nl": "aangepaste apparaten",
        "fr": "appareils personnalisés",
        "it": "dispositivi personalizzati",
        "es": "dispositivos personalizados",
        "pl": "urządzenia niestandardowe",
        "zh-cn": "定制设备"
      }


};