/*global systemDictionary:true */
"use strict";

// @ts-ignore
systemDictionary = {
    "device-reminder adapter settings": {
        "en": "Adapter settings for device-reminder",
        "de": "Adaptereinstellungen für device-reminder",
        "ru": "Настройки адаптера для device-reminder",
        "pt": "Configurações do adaptador para device-reminder",
        "nl": "Adapterinstellingen voor device-reminder",
        "fr": "Paramètres d'adaptateur pour device-reminder",
        "it": "Impostazioni dell'adattatore per device-reminder",
        "es": "Ajustes del adaptador para device-reminder",
        "pl": "Ustawienia adaptera dla device-reminder",
        "zh-cn": "device-reminder的适配器设置"
    },
    "Config": {
        "en": "Config",
        "de": "Konfiguration",
        "ru": "Конфиг",
        "pt": "Config",
        "nl": "Config",
        "fr": "Config",
        "it": "Config",
        "es": "Config",
        "pl": "Config",
        "zh-cn": "设定档"
      },
    "active": {
        "en": "active",
        "de": "aktiv",
        "ru": "активный",
        "pt": "ativo",
        "nl": "actief",
        "fr": "actif",
        "it": "attivo",
        "es": "activo",
        "pl": "aktywny",
        "zh-cn": "积极的"
    },
    "device": {
        "en": "device",
        "de": "Gerät",
        "ru": "устройство",
        "pt": "dispositivo",
        "nl": "apparaat",
        "fr": "appareil",
        "it": "dispositivo",
        "es": "dispositivo",
        "pl": "urządzenie",
        "zh-cn": "设备"
      },
      "alexa": {
        "en": "alexa",
        "de": "alexa",
        "ru": "Алекса",
        "pt": "alexa",
        "nl": "Alexa",
        "fr": "alexa",
        "it": "alexa",
        "es": "alexa",
        "pl": "alexa",
        "zh-cn": "亚历克斯"
      },
      "whatsapp": {
        "en": "whatsapp",
        "de": "WhatsApp",
        "ru": "WhatsApp",
        "pt": "Whatsapp",
        "nl": "whatsapp",
        "fr": "WhatsApp",
        "it": "WhatsApp",
        "es": "whatsapp",
        "pl": "WhatsApp",
        "zh-cn": "Whatsapp的"
      },
      "switch off": {
        "en": "switch off",
        "de": "ausschalten",
        "ru": "выключить",
        "pt": "desligar",
        "nl": "Uitzetten",
        "fr": "éteindre",
        "it": "spegnere",
        "es": "apagar",
        "pl": "wyłączyć",
        "zh-cn": "关掉"
      },
      "switch off after minutes": {
        "en": "switch off after minutes",
        "de": "Ausschalt-<br>verzögerung",
        "ru": "выключить<br>через<br>несколько<br>минут",
        "pt": "desligue<br>após<br>minutos",
        "nl": "uitschakelen<br>na minuten",
        "fr": "éteindre après<br>quelques minutes",
        "it": "spegnere dopo<br>minuti",
        "es": "apagar<br>después<br>de minutos",
        "pl": "wyłączyć<br>po minutach",
        "zh-cn": "几分钟后关闭"
      },
      "abort detection": {
        "en": "abort detection",
        "de": "Abbruch-<br>erkennung",
        "ru": "прервать<br>обнаружение",
        "pt": "detecção<br>de aborto",
        "nl": "de detectie<br>afbreken",
        "fr": "détection<br>d'abandon",
        "it": "interruzione<br>del<br>rilevamento",
        "es": "abortar la<br>detección",
        "pl": "przerwać<br>wykrywanie",
        "zh-cn": "中止检测"
      },

      "add device": {
        "en": "add device",
        "de": "Gerät hinzufügen",
        "ru": "добавить устройство",
        "pt": "Adicionar Dispositivo",
        "nl": "Voeg toestel toe",
        "fr": "ajouter un appareil",
        "it": "Aggiungi dispositivo",
        "es": "añadir dispositivo",
        "pl": "Dodaj urządzenie",
        "zh-cn": "添加设备"
      },
      "Input checked": {
        "en": "Input checked",
        "de": "Eingabe geprüft",
        "ru": "Ввод проверен",
        "pt": "Entrada verificada",
        "nl": "Input aangevinkt",
        "fr": "Entrée vérifiée",
        "it": "Input verificato",
        "es": "Entrada marcada",
        "pl": "Wejście sprawdzone",
        "zh-cn": "输入已检查"
      },
      "Required fields": {
        "en": "*Required fields",
        "de": "*Benötigte Felder",
        "ru": "* Обязательные поля",
        "pt": "*Os campos obrigatórios",
        "nl": "*Verplichte velden",
        "fr": "*Champs obligatoires",
        "it": "*Campi richiesti",
        "es": "*Campos requeridos",
        "pl": "*Wymagane pola",
        "zh-cn": "*必填项"
      },
      "close": {
        "en": "close",
        "de": "schließen",
        "ru": "Закрыть",
        "pt": "perto",
        "nl": "dichtbij",
        "fr": "Fermer",
        "it": "vicino",
        "es": "cerca",
        "pl": "blisko",
        "zh-cn": "关闭"
      },
      "save": {
        "en": "save",
        "de": "speichern",
        "ru": "спасти",
        "pt": "Salve ",
        "nl": "sparen",
        "fr": "sauvegarder",
        "it": "Salva",
        "es": "ahorrar",
        "pl": "zapisać",
        "zh-cn": "保存"
      },
      "Edit %s": {
        "en": "Edit %s",
        "de": "%s bearbeiten",
        "ru": "Изменить %s ",
        "pt": "Editar %s ",
        "nl": "Bewerk %s ",
        "fr": "Modifier %s ",
        "it": "Modifica %s ",
        "es": "Editar %s ",
        "pl": "Edytuj %s ",
        "zh-cn": "编辑％s"
      },
      "Create %s": {
        "en": "Create %s",
        "de": "%s erstellen ",
        "ru": "Создать %s ",
        "pt": "Crie %s ",
        "nl": "Maak %s  aan",
        "fr": "Créer %s ",
        "it": "Crea %s ",
        "es": "Crear %s ",
        "pl": "Utwórz %s ",
        "zh-cn": "创建％s"
      },
      "Error(s) found in configuration": {
        "en": "Error(s) found in configuration",
        "de": "Fehler in der Konfiguration gefunden",
        "ru": "В конфигурации обнаружены ошибки",
        "pt": "Erro (s) encontrado (s) na configuração",
        "nl": "Fout (en) gevonden in configuratie",
        "fr": "Erreur (s) trouvée (s) dans la configuration",
        "it": "Errori trovati nella configurazione",
        "es": "Error (s) encontrado en la configuración",
        "pl": "Znaleziono błędy w konfiguracji",
        "zh-cn": "配置中发现错误"
      },
      "Error(s) found in %s": {
        "en": "Error(s) found in %s",
        "de": "Fehler in %s gefunden",
        "ru": "Обнаружены ошибки в %s",
        "pt": "Erro (s) encontrado (s) em %s",
        "nl": "Fout (en) gevonden in %s",
        "fr": "Erreur (s) trouvée (s) dans %s",
        "it": "Errori trovati in %s",
        "es": "Error (s) encontrado en %s",
        "pl": "Znaleziono błędy w %s",
        "zh-cn": "％s中发现错误"
      },
      "invalid input detected": {
        "en": "invalid input detected",
        "de": "ungültige Eingabe erkannt",
        "ru": "обнаружен неверный ввод",
        "pt": "entrada inválida detectada",
        "nl": "ongeldige invoer gedetecteerd",
        "fr": "entrée non valide détectée",
        "it": "rilevato input non valido",
        "es": "entrada inválida detectada",
        "pl": "wykryto nieprawidłowe dane wejściowe",
        "zh-cn": "检测到无效输入"
      },
      "no entries found": {
        "en": "no entries found",
        "de": "Keine Einträge gefunden",
        "ru": "записей не найдено",
        "pt": "nenhuma entrada encontrada",
        "nl": "geen items gevonden",
        "fr": "aucune entrée trouvée",
        "it": "nessuna voce trovata",
        "es": "entradas no encontradas",
        "pl": "nie znaleziono wpisów",
        "zh-cn": "找不到条目"
      },
      "Pls check input": {
        "en": "Pls check input",
        "de": "Bitte überprüfen Sie die Eingabe",
        "ru": "Пожалуйста, проверьте ввод",
        "pt": "Por favor, verifique a entrada",
        "nl": "Controleer de invoer",
        "fr": "Veuillez vérifier l'entrée",
        "it": "Ingresso di controllo di Pls",
        "es": "Por favor, compruebe la entrada",
        "pl": "Pls sprawdź dane wejściowe",
        "zh-cn": "请检查输入"
      },
      "help": {
        "en": "help",
        "de": "Hilfe",
        "ru": "помощь",
        "pt": "ajuda",
        "nl": "helpen",
        "fr": "aider",
        "it": "Aiuto",
        "es": "ayuda",
        "pl": "Wsparcie",
        "zh-cn": "帮助"
      },
      "devices": {
        "en": "devices",
        "de": "Geräte",
        "ru": "устройства",
        "pt": "dispositivos",
        "nl": "apparaten",
        "fr": "dispositifs",
        "it": "dispositivi",
        "es": "dispositivos",
        "pl": "urządzenia",
        "zh-cn": "设备"
      },
      "device name": {
        "en": "*device name",
        "de": "*Gerätename",
        "ru": "*имя устройства",
        "pt": "*nome do dispositivo",
        "nl": "*toestelnaam",
        "fr": "*nom de l'appareil",
        "it": "*nome del dispositivo",
        "es": "*nombre del dispositivo",
        "pl": "*Nazwa urządzenia",
        "zh-cn": "*设备名称"
      },
      "device type": {
        "en": "*device type",
        "de": "*Gerätetyp",
        "ru": "*тип устройства",
        "pt": "*tipo de dispositivo",
        "nl": "*soort apparaat",
        "fr": "*type d'appareil",
        "it": "*tipo di dispositivo",
        "es": "*tipo de dispositivo",
        "pl": "*rodzaj urządzenia",
        "zh-cn": "*设备类型"
      },
      "consumption": {
        "en": "*consumption",
        "de": "*Verbrauch",
        "ru": "*потребление",
        "pt": "*consumo",
        "nl": "*verbruik",
        "fr": "*consommation",
        "it": "*consumo",
        "es": "*consumo",
        "pl": "*zużycie",
        "zh-cn": "消耗/能源"
      },
      "totalConsumption": {
        "en": "Total consumption",
        "de": "Gesamter Verbrauch",
        "ru": "Total consumption",
        "pt": "Total consumption",
        "nl": "Total consumption",
        "fr": "Total consumption",
        "it": "Total consumption",
        "es": "Total consumption",
        "pl": "Total consumption",
        "zh-cn": "Total consumption"
      },
      "Power switch": {
        "en": "Power switch",
        "de": "Schalter AN/AUS",
        "ru": "Выключатель",
        "pt": "Interruptor de energia",
        "nl": "Aan / uit-schakelaar",
        "fr": "Interrupteur",
        "it": "Interruttore di alimentazione",
        "es": "Interruptor de alimentación",
        "pl": "Włącznik zasilania",
        "zh-cn": "开关;电源开关"
      },
      "starttext": {
        "en": "starttext",
        "de": "Starttext",
        "ru": "starttext",
        "pt": "texto inicial",
        "nl": "starttekst",
        "fr": "texte de départ",
        "it": "starttext",
        "es": "starttext",
        "pl": "tekst startowy",
        "zh-cn": "起始文本"
      },
      "endtext": {
        "en": "endtext",
        "de": "Endtext",
        "ru": "конечный текст",
        "pt": "texto final",
        "nl": "endtext",
        "fr": "fin de texte",
        "it": "endtext",
        "es": "endtext",
        "pl": "tekst końcowy",
        "zh-cn": "结束语"
      },
      "delete": {
        "en": "delete",
        "de": "löschen",
        "ru": "Удалить",
        "pt": "excluir",
        "nl": "verwijderen",
        "fr": "effacer",
        "it": "Elimina",
        "es": "Eliminar",
        "pl": "kasować",
        "zh-cn": "删除"
      },

      "*name": {
        "en": "*name",
        "de": "*Name",
        "ru": "*название",
        "pt": "*nome",
        "nl": "*naam",
        "fr": "*Nom",
        "it": "*nome",
        "es": "*nombre",
        "pl": "*Nazwa",
        "zh-cn": "*名称"
      },
      "active from hour": {
        "en": "active from hour",
        "de": "aktiv ab Stunde",
        "ru": "активен с часа",
        "pt": "ativo de hora",
        "nl": "actief vanaf uur",
        "fr": "actif à partir de l'heure",
        "it": "attivo da ora",
        "es": "activo desde la hora",
        "pl": "aktywny od godz",
        "zh-cn": "从小时开始活动"
      },
      "active from minute": {
        "en": "active from minute",
        "de": "aktiv ab Minute",
        "ru": "активен с минуты",
        "pt": "ativo desde o minuto",
        "nl": "actief vanaf minuut",
        "fr": "actif de la minute",
        "it": "attivo dal minuto",
        "es": "activo desde el minuto",
        "pl": "aktywny od minuty",
        "zh-cn": "从分钟开始活跃"
      },
      "inactive from hour": {
        "en": "inactive from hour",
        "de": "deaktiviert ab Stunde",
        "ru": "неактивен с часа",
        "pt": "inativo desde a hora",
        "nl": "inactief vanaf uur",
        "fr": "inactif depuis l'heure",
        "it": "inattivo da ora",
        "es": "inactivo desde hora",
        "pl": "nieaktywne od godz",
        "zh-cn": "从小时开始不活动"
      },
      "inactive from minute": {
        "en": "inactive from minute",
        "de": "deaktiviert ab Minute",
        "ru": "неактивен с минуты",
        "pt": "inativo desde o minuto",
        "nl": "inactief vanaf minuut",
        "fr": "inactif de minute",
        "it": "inattivo dal minuto",
        "es": "inactivo desde el minuto",
        "pl": "nieaktywne od minuty",
        "zh-cn": "从分钟开始无效"
      },

      "*pushover instance": {
        "en": "*pushover instance",
        "de": "* Pushover-Instanz",
        "ru": "* экземпляр pushover",
        "pt": "* instância pushover",
        "nl": "* pushover-instantie",
        "fr": "* instance pushover",
        "it": "* istanza pushover",
        "es": "* instancia fácil",
        "pl": "* instancja pushover",
        "zh-cn": "*推送实例"
      },
      "*priority": {
        "en": "*priority",
        "de": "*Priorität",
        "ru": "* приоритет",
        "pt": "*prioridade",
        "nl": "*prioriteit",
        "fr": "*priorité",
        "it": "*priorità",
        "es": "*prioridad",
        "pl": "*priorytet",
        "zh-cn": "*优先事项"
      },
      "*sound": {
        "en": "*sound",
        "de": "*Ton",
        "ru": "*звук",
        "pt": "*som",
        "nl": "*geluid",
        "fr": "*sonner",
        "it": "*suono",
        "es": "*sonar",
        "pl": "*dźwięk",
        "zh-cn": "*声音"
      },

      "*sender address": {
        "en": "*sender address",
        "de": "*Absenderadresse",
        "ru": "* адрес отправителя",
        "pt": "*Endereço do remetente",
        "nl": "*Zender adres",
        "fr": "*adresse de l'expéditeur",
        "it": "* indirizzo del mittente",
        "es": "*dirección del remitente",
        "pl": "*adres nadawcy",
        "zh-cn": "*发件人地址"
      },
      "*receiver address": {
        "en": "*receiver address",
        "de": "*Empfängeradresse",
        "ru": "* адрес получателя",
        "pt": "* endereço do receptor",
        "nl": "* adres ontvanger",
        "fr": "* adresse du destinataire",
        "it": "* indirizzo del destinatario",
        "es": "* dirección del receptor",
        "pl": "*Odbiorca adres",
        "zh-cn": "*收货人地址"
      },

      "default device types": {
        "en": "default device types",
        "de": "Standardgerätetypen",
        "ru": "типы устройств по умолчанию",
        "pt": "tipos de dispositivo padrão",
        "nl": "standaard apparaattypen",
        "fr": "types d'appareils par défaut",
        "it": "tipi di dispositivi predefiniti",
        "es": "tipos de dispositivos predeterminados",
        "pl": "domyślne typy urządzeń",
        "zh-cn": "默认设备类型"
      },
      "custom device types": {
        "en": "custom device types",
        "de": "Benutzerdefinierte Gerätetypen",
        "ru": "пользовательские типы устройств",
        "pt": "tipos de dispositivos personalizados",
        "nl": "aangepaste apparaattypen",
        "fr": "types d'appareils personnalisés",
        "it": "tipi di dispositivi personalizzati",
        "es": "tipos de dispositivos personalizados",
        "pl": "niestandardowe typy urządzeń",
        "zh-cn": "定制设备类型"
      },
      "name": {
        "en": "name",
        "de": "Name",
        "ru": "название",
        "pt": "nome",
        "nl": "naam",
        "fr": "Nom",
        "it": "nome",
        "es": "nombre",
        "pl": "Nazwa",
        "zh-cn": "名称"
      },
      "threshold 'start' (watt)": {
        "en": "threshold 'start' (watt)",
        "de": "Schwellwert 'Start' (Watt)",
        "ru": "порог «старт» (ватт)",
        "pt": "limite 'início' (watt)",
        "nl": "drempel 'start' (watt)",
        "fr": "seuil 'start' (watt)",
        "it": "soglia 'inizio' (watt)",
        "es": "umbral 'inicio' (vatios)",
        "pl": "próg „start” (wat)",
        "zh-cn": "阈值“开始”（瓦特）"
      },
      "threshold 'end' (watt)": {
        "en": "threshold 'end' (watt)",
        "de": "Schwellwert 'Ende' (Watt)",
        "ru": "порог 'конец' (ватт)",
        "pt": "limite 'fim' (watt)",
        "nl": "drempel 'einde' (watt)",
        "fr": "seuil 'fin' (watt)",
        "it": "soglia 'fine' (watt)",
        "es": "umbral 'fin' (vatios)",
        "pl": "próg „koniec” (wat)",
        "zh-cn": "阈值“结束”（瓦特）"
      },
      "threshold 'standby' (watt)": {
        "en": "threshold 'standby' (watt)",
        "de": "Schwellwert 'Standby' (Watt)",
        "ru": "порог ожидания (ватт)",
        "pt": "limite 'espera' (watt)",
        "nl": "drempel 'standby' (watt)",
        "fr": "seuil 'veille' (watt)",
        "it": "soglia 'standby' (watt)",
        "es": "umbral 'en espera' (vatios)",
        "pl": "próg czuwania (wat)",
        "zh-cn": "阈值“待机”（瓦特）"
      },
      "number of 'start' values": {
        "en": "number of 'start' values",
        "de": "Anzahl Startwerte",
        "ru": "количество \"начальных\" значений",
        "pt": "número de valores 'iniciais'",
        "nl": "aantal 'start'-waarden",
        "fr": "nombre de valeurs de «début»",
        "it": "numero di valori \"iniziali\"",
        "es": "número de valores de 'inicio'",
        "pl": "liczba wartości „początkowych”",
        "zh-cn": "“开始”值的数量"
      },
      "number of ​'end' values": {
        "en": "number of ​'end' values",
        "de": "Anzahl Endwerte",
        "ru": "количество \"конечных\" значений",
        "pt": "número de valores 'finais'",
        "nl": "aantal 'eind'-waarden",
        "fr": "nombre de valeurs de «fin»",
        "it": "numero di valori \"end\"",
        "es": "número de valores 'finales'",
        "pl": "liczba wartości „końcowych”",
        "zh-cn": "``结束''值的数量"
      },

      "device status": {
        "en": "device status",
        "de": "Gerätestatus",
        "ru": "состояние устройства",
        "pt": "status do dispositivo",
        "nl": "Apparaatstatus",
        "fr": "statut du périphérique",
        "it": "stato del dispositivo",
        "es": "estado del dispositivo",
        "pl": "status urządzenia",
        "zh-cn": "设备状态"
      },
      "status: 'in action'": {
        "en": "status: 'in action'",
        "de": "Status: 'in Aktion'",
        "ru": "статус: «в действии»",
        "pt": "status: 'em ação'",
        "nl": "status: 'in actie'",
        "fr": "statut: 'en action'",
        "it": "stato: \"in azione\"",
        "es": "estado: 'en acción'",
        "pl": "status: „w akcji”",
        "zh-cn": "状态：“执行中”"
      },
      "status: 'standby'": {
        "en": "status: 'standby'",
        "de": "Status: 'Standby'",
        "ru": "статус: «в режиме ожидания»",
        "pt": "status: 'standby'",
        "nl": "status: 'standby'",
        "fr": "état: 'veille'",
        "it": "stato: \"standby\"",
        "es": "estado: 'en espera'",
        "pl": "status: 'czuwanie'",
        "zh-cn": "状态：“待命”"
      },
      "status: 'device off'": {
        "en": "status: 'device off'",
        "de": "Status: 'Gerät aus'",
        "ru": "статус: 'устройство выключено'",
        "pt": "status: 'dispositivo desligado'",
        "nl": "status: 'apparaat uit'",
        "fr": "état: 'appareil éteint'",
        "it": "stato: \"dispositivo spento\"",
        "es": "estado: 'dispositivo apagado'",
        "pl": "status: „urządzenie wyłączone”",
        "zh-cn": "状态：“设备关闭”"
      }

};