/*global systemDictionary:true */
"use strict";

// @ts-ignore
systemDictionary = {
    "Monitoring of devices based on consumption": {
        "en": "Monitoring of devices based on consumption",
        "de": "Überwachung von Geräten anhand des Verbrauchs",
        "ru": "Мониторинг устройств на основе потребления",
        "pt": "Monitoramento de dispositivos com base no consumo",
        "nl": "Toezicht op apparaten op basis van verbruik",
        "fr": "Suivi des appareils en fonction de la consommation",
        "it": "Monitoraggio dei dispositivi in base ai consumi",
        "es": "Monitorización de dispositivos en función del consumo",
        "pl": "Monitoring urządzeń na podstawie zużycia",
        "zh-cn": "基于消耗的设备监控"
    },
    "Configuration": {
        "en": "Configuration",
        "de": "Konfiguration",
        "ru": "Конфигурация",
        "pt": "Configuração",
        "nl": "Configuratie",
        "fr": "Configuration",
        "it": "Configurazione",
        "es": "Configuración",
        "pl": "Konfiguracja",
        "zh-cn": "配置"
    },
    "active": {
        "en": "active",
        "de": "aktiv",
        "ru": "активный",
        "pt": "ativo",
        "nl": "actief",
        "fr": "actif",
        "it": "attivo",
        "es": "activo",
        "pl": "aktywny",
        "zh-cn": "积极的"
    },
    "add": {
        "en": "add",
        "de": "hinzufügen",
        "ru": "добавить",
        "pt": "adicionar",
        "nl": "_",
        "fr": "ajouter",
        "it": "aggiungere",
        "es": "añadir",
        "pl": "dodać",
        "zh-cn": "增 编"
    },
    "linked devices": {
        "en": "Linked devices",
        "de": "Verknüpfte Geräte",
        "ru": "Связанные устройства",
        "pt": "Dispositivos ligados",
        "nl": "Vertaling:",
        "fr": "Appareils connectés",
        "it": "Dispositivi collegati",
        "es": "Dispositivos vinculados",
        "pl": "Urządzenia linkujące",
        "zh-cn": "联系装置"
    },
    "measuringDevice": {
        "en": "Measuring device / socket",
        "de": "Messgerät / Steckdose",
        "ru": "Измерительное устройство / розетка",
        "pt": "Dispositivo de medição / soquete",
        "nl": "Vermenigvuldigen apparaat / socket",
        "fr": "Appareil de mesure / prise",
        "it": "Dispositivo di misura / presa",
        "es": "Dispositivo de medición / toma",
        "pl": "Measuring device / gniazdo",
        "zh-cn": "测量装置/装置"
    },
    "device": {
        "en": "device",
        "de": "Gerät",
        "ru": "устройство",
        "pt": "dispositivo",
        "nl": "apparaat",
        "fr": "appareil",
        "it": "dispositivo",
        "es": "dispositivo",
        "pl": "urządzenie",
        "zh-cn": "设备"
    },
    "switch off": {
        "en": "switch off",
        "de": "ausschalten",
        "ru": "выключить",
        "pt": "desligar",
        "nl": "Uitzetten",
        "fr": "éteindre",
        "it": "spegnere",
        "es": "apagar",
        "pl": "wyłączyć",
        "zh-cn": "关掉"
    },
    "switch off after minutes": {
        "en": "switch off after minutes",
        "de": "Abschalten nach Minuten",
        "ru": "выключить через несколько минут",
        "pt": "desligue após minutos",
        "nl": "na minuten uitschakelen",
        "fr": "s'éteint après quelques minutes",
        "it": "si spegne dopo pochi minuti",
        "es": "apagar después de minutos",
        "pl": "wyłącz po minutach",
        "zh-cn": "几分钟后关闭"
    },
    "abort detection": {
        "en": "abort detection",
        "de": "Abbrucherkennung",
        "ru": "прервать обнаружение",
        "pt": "detecção de aborto",
        "nl": "detectie afbreken",
        "fr": "abandonner la détection",
        "it": "interruzione del rilevamento",
        "es": "abortar la detección",
        "pl": "przerwać wykrywanie",
        "zh-cn": "中止检测"
    },
    "devices": {
        "en": "devices",
        "de": "Geräte",
        "ru": "устройства",
        "pt": "dispositivos",
        "nl": "apparaten",
        "fr": "dispositifs",
        "it": "dispositivi",
        "es": "dispositivos",
        "pl": "urządzenia",
        "zh-cn": "设备"
    },
    "Input checked": {
        "en": "Input checked",
        "de": "Eingabe überprüft",
        "ru": "Ввод проверен",
        "pt": "Entrada verificada",
        "nl": "Invoer aangevinkt",
        "fr": "Entrée cochée",
        "it": "Input controllato",
        "es": "Entrada marcada",
        "pl": "Wejście sprawdzone",
        "zh-cn": "输入检查"
    },
    "help": {
        "en": "help",
        "de": "Hilfe",
        "ru": "помощь",
        "pt": "ajuda",
        "nl": "helpen",
        "fr": "aider",
        "it": "aiuto",
        "es": "ayudar",
        "pl": "Wsparcie",
        "zh-cn": "帮助"
    },
    "*Required fields": {
        "en": "*Required fields",
        "de": "*Felder erforderlich",
        "ru": "*Обязательные поля",
        "pt": "*Os campos obrigatórios",
        "nl": "*Verplichte velden",
        "fr": "*Champs obligatoires",
        "it": "*Campi richiesti",
        "es": "*Campos requeridos",
        "pl": "*Wymagane pola",
        "zh-cn": "*必填字段"
    },
    "device name": {
        "en": "device name",
        "de": "Gerätename",
        "ru": "имя устройства",
        "pt": "nome do dispositivo",
        "nl": "toestelnaam",
        "fr": "nom de l'appareil",
        "it": "nome del dispositivo",
        "es": "nombre del dispositivo",
        "pl": "Nazwa urządzenia",
        "zh-cn": "设备名称"
    },
    "device type": {
        "en": "device type",
        "de": "Gerätetyp",
        "ru": "тип устройства",
        "pt": "tipo de dispositivo",
        "nl": "soort apparaat",
        "fr": "type d'appareil",
        "it": "tipo di dispositivo",
        "es": "tipo de dispositivo",
        "pl": "rodzaj urządzenia",
        "zh-cn": "设备类型",
    },
    "consumption": {
        "en": "consumption",
        "de": "Verbrauch",
        "ru": "потребление",
        "pt": "consumo",
        "nl": "consumptie",
        "fr": "consommation",
        "it": "consumo",
        "es": "consumo",
        "pl": "konsumpcja",
        "zh-cn": "消耗"
    },
    "Power switch": {
        "en": "Power switch",
        "de": "Stromschalter",
        "ru": "Выключатель",
        "pt": "Interruptor de energia",
        "nl": "Aan/uit-schakelaar:",
        "fr": "Interrupteur",
        "it": "Interruttore di alimentazione",
        "es": "Interruptor de alimentación",
        "pl": "Włącznik zasilania",
        "zh-cn": "开关;电源开关"
    },
    "starttext": {
        "en": "starttext",
        "de": "Starttext",
        "ru": "стартовый текст",
        "pt": "texto inicial",
        "nl": "starttekst",
        "fr": "texte de début",
        "it": "testo iniziale",
        "es": "texto de inicio",
        "pl": "tekst startowy",
        "zh-cn": "开始文本"
    },
    "endtext": {
        "en": "endtext",
        "de": "Endtext",
        "ru": "конечный текст",
        "pt": "texto final",
        "nl": "eindtekst",
        "fr": "texte de fin",
        "it": "testo finale",
        "es": "texto final",
        "pl": "tekst końcowy",
        "zh-cn": "正文"
    },
    "delete": {
        "en": "delete",
        "de": "löschen",
        "ru": "удалять",
        "pt": "excluir",
        "nl": "verwijderen",
        "fr": "effacer",
        "it": "eliminare",
        "es": "Eliminar",
        "pl": "usunąć",
        "zh-cn": "删除"
    },
    "Pls check input": {
        "en": "Pls check input",
        "de": "Bitte Eingabe prüfen",
        "ru": "Пожалуйста, проверьте ввод",
        "pt": "Por favor, verifique a entrada",
        "nl": "Pls check input",
        "fr": "Veuillez vérifier l'entrée",
        "it": "Si prega di controllare l'input",
        "es": "Por favor verifique la entrada",
        "pl": "Pls sprawdź wejście!",
        "zh-cn": "请检查输入"
    },
    "invalid input detected": {
        "en": "invalid input detected",
        "de": "Ungültige Eingabe erkannt",
        "ru": "обнаружен неверный ввод",
        "pt": "entrada inválida detectada",
        "nl": "ongeldige invoer gedetecteerd",
        "fr": "entrée invalide détectée",
        "it": "è stato rilevato un input non valido",
        "es": "entrada no válida detectada",
        "pl": "wykryto nieprawidłowe dane wejściowe",
        "zh-cn": "检测到无效输入"
    },
    "*volume 0-100": {
        "en": "*volume 0-100",
        "de": "*Lautstärke 0-100",
        "ru": "*громкость 0-100",
        "pt": "*volume 0-100",
        "nl": "*volume 0-100",
        "fr": "*volume 0-100",
        "it": "*volume 0-100",
        "es": "*volumen 0-100",
        "pl": "*objętość 0-100",
        "zh-cn": "*音量 0-100"
    },
    "active from": {
        "en": "Active from",
        "de": "Aktiv von",
        "ru": "Активно из",
        "pt": "Activo",
        "nl": "Actie van",
        "fr": "Actif",
        "it": "Attivo da",
        "es": "Activo desde",
        "pl": "Aktywna od",
        "zh-cn": "行为"
    },
    "active until": {
        "en": "Active until",
        "de": "Aktiv bis",
        "ru": "Активно до",
        "pt": "Activo até",
        "nl": "Actie tot",
        "fr": "Active jusqu'à",
        "it": "Attivo fino a quando",
        "es": "Activo hasta",
        "pl": "Aktywny do czasu aż",
        "zh-cn": "直至行动"
    },
    "no entries found": {
        "en": "no entries found",
        "de": "Keine Einträge gefunden",
        "ru": "записей не найдено",
        "pt": "nenhuma entrada encontrada",
        "nl": "geen inzendingen gevonden",
        "fr": "aucune entrée trouvée",
        "it": "nessuna voce trovata",
        "es": "entradas no encontradas",
        "pl": "nie znaleziono wpisów",
        "zh-cn": "未找到条目"
    },
    "*pushover instance": {
        "en": "*pushover instance",
        "de": "*Pushover-Instanz",
        "ru": "* пуш-овер экземпляр",
        "pt": "*instância de pushover",
        "nl": "*pushover-instantie",
        "fr": "*instance de transfert",
        "it": "*istanza pushover",
        "es": "*instancia pushover",
        "pl": "*instancja pushover",
        "zh-cn": "*推送实例"
    },
    "*priority": {
        "en": "*priority",
        "de": "*Priorität",
        "ru": "* приоритет",
        "pt": "*prioridade",
        "nl": "*prioriteit",
        "fr": "*priorité",
        "it": "*priorità",
        "es": "*prioridad",
        "pl": "*priorytet",
        "zh-cn": "*优先事项"
    },
    "*sound": {
        "en": "*sound",
        "de": "*Klang",
        "ru": "*звук",
        "pt": "*som",
        "nl": "*geluid",
        "fr": "*son",
        "it": "*suono",
        "es": "*sonar",
        "pl": "*dźwięk",
        "zh-cn": "*声音"
    },
    "*name": {
        "en": "*name",
        "de": "*Name",
        "ru": "*название",
        "pt": "*nome",
        "nl": "*naam",
        "fr": "*Nom",
        "it": "*nome",
        "es": "*nombre",
        "pl": "*nazwać",
        "zh-cn": "*姓名"
    },
    "name": {
        "en": "name",
        "de": "Name",
        "ru": "название",
        "pt": "nome",
        "nl": "naam",
        "fr": "Nom",
        "it": "nome",
        "es": "nombre",
        "pl": "nazwać",
        "zh-cn": "姓名"
    },
    "*sender address": {
        "en": "*sender address",
        "de": "*Absenderadresse",
        "ru": "*адрес отправителя",
        "pt": "*Endereço do remetente",
        "nl": "*Zender adres",
        "fr": "*adresse de l'expéditeur",
        "it": "*indirizzo del mittente",
        "es": "*dirección del remitente",
        "pl": "*adres nadawcy",
        "zh-cn": "*发件人地址"
    },
    "*receiver address": {
        "en": "*receiver address",
        "de": "*Empfängeradresse",
        "ru": "*адрес получателя",
        "pt": "*endereço do destinatário",
        "nl": "*ontvanger adres",
        "fr": "*adresse du destinataire",
        "it": "*indirizzo del destinatario",
        "es": "*dirección del destinatario",
        "pl": "*Odbiorca adres",
        "zh-cn": "*收件人地址"
    },
    "default type config": {
        "en": "default type config",
        "de": "Gerätewerte Standard",
        "ru": "конфигурация типа по умолчанию",
        "pt": "configuração de tipo padrão",
        "nl": "standaard type configuratie",
        "fr": "configuration de type par défaut",
        "it": "tipo predefinito config",
        "es": "configuración de tipo predeterminada",
        "pl": "domyślna konfiguracja typu",
        "zh-cn": "默认类型配置"
    },
    "custom type config": {
        "en": "custom type config",
        "de": "Gerätewerte User",
        "ru": "конфигурация пользовательского типа",
        "pt": "configuração de tipo personalizado",
        "nl": "aangepast type configuratie",
        "fr": "configuration de type personnalisée",
        "it": "tipo personalizzato config",
        "es": "configuración de tipo personalizado",
        "pl": "konfiguracja typu niestandardowego",
        "zh-cn": "自定义类型配置"
    },
    "threshold 'start' (watt)": {
        "en": "threshold 'start' (watt)",
        "de": "Schwelle 'Start' (Watt)",
        "ru": "порог «старт» (ватт)",
        "pt": "limite 'iniciar' (watt)",
        "nl": "drempel 'start' (watt)",
        "fr": "seuil 'start' (watt)",
        "it": "soglia 'start' (watt)",
        "es": "umbral 'inicio' (vatios)",
        "pl": "próg „start” (wat)",
        "zh-cn": "阈值“开始”（瓦特）"
    },
    "threshold 'end' (watt)": {
        "en": "threshold 'end' (watt)",
        "de": "Schwelle 'Ende' (Watt)",
        "ru": "порог «конец» (ватт)",
        "pt": "limite 'fim' (watt)",
        "nl": "drempel 'eind' (watt)",
        "fr": "seuil 'fin' (watt)",
        "it": "soglia 'fine' (watt)",
        "es": "umbral 'fin' (vatios)",
        "pl": "próg „koniec” (wat)",
        "zh-cn": "阈值“结束”（瓦特）"
    },
    "threshold 'standby' (watt)": {
        "en": "threshold 'standby' (watt)",
        "de": "Schwelle 'Standby' (Watt)",
        "ru": "порог «ожидания» (ватт)",
        "pt": "limiar 'standby' (watt)",
        "nl": "drempel 'standby' (watt)",
        "fr": "seuil 'veille' (watt)",
        "it": "soglia 'standby' (watt)",
        "es": "umbral 'en espera' (vatios)",
        "pl": "próg czuwania (wat)",
        "zh-cn": "阈值“待机”（瓦特）"
    },
    "number of 'start' values": {
        "en": "number of 'start' values",
        "de": "Anzahl der 'Start'-Werte",
        "ru": "количество «начальных» значений",
        "pt": "número de valores 'iniciais'",
        "nl": "aantal 'start'-waarden",
        "fr": "nombre de valeurs 'début'",
        "it": "numero di valori 'iniziali'",
        "es": "número de valores de 'inicio'",
        "pl": "liczba wartości „początkowych”",
        "zh-cn": "“开始”值的数量"
    },
    "number of ​'end' values": {
        "en": "number of ​'end' values",
        "de": "Anzahl der ​'End'-Werte",
        "ru": "количество «конечных» значений",
        "pt": "número de valores 'final'",
        "nl": "aantal ​'eind'-waarden",
        "fr": "nombre de valeurs \"fin\"",
        "it": "numero di \"valori finali\".",
        "es": "número de valores 'finales'",
        "pl": "liczba ​wartości końcowych",
        "zh-cn": "“结束”值的数量"
    },
    "device status": {
        "en": "device status",
        "de": "Gerätestatus",
        "ru": "состояние устройства",
        "pt": "status do dispositivo",
        "nl": "Apparaatstatus",
        "fr": "statut du périphérique",
        "it": "stato del dispositivo",
        "es": "estado del dispositivo",
        "pl": "status urządzenia",
        "zh-cn": "设备状态"
    },
    "status: 'in action'": {
        "en": "status: 'in action'",
        "de": "Status: 'in Aktion'",
        "ru": "статус: \"в действии\"",
        "pt": "estado: 'em ação'",
        "nl": "status: 'in actie'",
        "fr": "statut : 'en action'",
        "it": "stato: 'in azione'",
        "es": "estado: 'en acción'",
        "pl": "status: „w akcji”",
        "zh-cn": "状态：'在行动'"
    },
    "status: 'standby'": {
        "en": "status: 'standby'",
        "de": "Status: 'Standby'",
        "ru": "статус: «ожидание»",
        "pt": "estado: 'em espera'",
        "nl": "status: 'stand-by'",
        "fr": "état : 'en attente'",
        "it": "stato: 'standby'",
        "es": "estado: 'en espera'",
        "pl": "status: „gotowość”",
        "zh-cn": "状态：“待命”"
    },
    "status: 'device off'": {
        "en": "status: 'device off'",
        "de": "Status: 'Gerät aus'",
        "ru": "статус: \"устройство выключено\"",
        "pt": "status: 'dispositivo desligado'",
        "nl": "status: 'apparaat uit'",
        "fr": "statut : \"appareil éteint\"",
        "it": "stato: 'dispositivo spento'",
        "es": "estado: 'dispositivo apagado'",
        "pl": "status: „urządzenie wyłączone”",
        "zh-cn": "状态：“设备关闭”"
    },
    "telegram user": {
        "en": "telegram user",
        "de": "Telegrambenutzer",
        "ru": "пользователь телеграммы",
        "pt": "usuário de telegrama",
        "nl": "telegram gebruiker",
        "fr": "utilisateur de télégramme",
        "it": "utente del telegramma",
        "es": "usuario de telegramas",
        "pl": "użytkownik telegramu",
        "zh-cn": "电报用户"
    },
    "telegram": {
        "en": "telegram",
        "de": "Telegram",
        "ru": "telegram",
        "pt": "telegram",
        "nl": "telegram",
        "fr": "telegram",
        "it": "telegram",
        "es": "telegram",
        "pl": "telegram",
        "zh-cn": "telegram"
    },
    "whatsapp user": {
        "en": "whatsapp user",
        "de": "WhatsApp-Benutzer",
        "ru": "пользователь WhatsApp",
        "pt": "usuário whatsapp",
        "nl": "whatsapp-gebruiker",
        "fr": "utilisateur WhatsApp",
        "it": "utente whatsapp",
        "es": "usuario de whatsapp",
        "pl": "użytkownik WhatsApp",
        "zh-cn": "whatsapp用户"
    },
    "whatsapp": {
        "en": "whatsapp",
        "de": "WhatsApp",
        "ru": "WhatsApp",
        "pt": "Whatsapp",
        "nl": "whatsapp",
        "fr": "WhatsApp",
        "it": "WhatsApp",
        "es": "whatsapp",
        "pl": "whatsapp",
        "zh-cn": "whatsapp"
    },
    "alexa": {
        "en": "alexa",
        "de": "Alexa",
        "ru": "alexa",
        "pt": "alexa",
        "nl": "alexa",
        "fr": "alexa",
        "it": "alexa",
        "es": "alexa",
        "pl": "alexa",
        "zh-cn": "alexa"
    },
    "pushover user": {
        "en": "pushover user",
        "de": "Pushover-Benutzer",
        "ru": "слабый пользователь",
        "pt": "usuário simples",
        "nl": "pushover gebruiker",
        "fr": "utilisateur pushover",
        "it": "utente pushover",
        "es": "usuario pushover",
        "pl": "użytkownik pushover",
        "zh-cn": "推倒用户"
    },
    "pushover": {
        "en": "pushover",
        "de": "Pushover",
        "ru": "pushover",
        "pt": "pushover",
        "nl": "pushover",
        "fr": "pushover",
        "it": "pushover",
        "es": "pushover",
        "pl": "pushover",
        "zh-cn": "pushover"
    },
    "email account": {
        "en": "email account",
        "de": "Email-Konto",
        "ru": "адрес электронной почты",
        "pt": "conta de e-mail",
        "nl": "email account",
        "fr": "compte email",
        "it": "account email",
        "es": "cuenta de correo electrónico",
        "pl": "Konto e-mail",
        "zh-cn": "电子邮件帐户"
    },
    "email": {
        "en": "email",
        "de": "Email",
        "ru": "Эл. адрес",
        "pt": "o email",
        "nl": "e-mail",
        "fr": "e-mail",
        "it": "e-mail",
        "es": "Email",
        "pl": "e-mail",
        "zh-cn": "电子邮件"
    },
    "sayit device": {
        "en": "sayit device",
        "de": "Sayit-Gerät",
        "ru": "скажи устройство",
        "pt": "dispositivo sayit",
        "nl": "Sayit-apparaat",
        "fr": "dis-le dispositif",
        "it": "dispositivo di dirlo",
        "es": "dilo dispositivo",
        "pl": "powiedz urządzenie",
        "zh-cn": "sayit 设备"
    },
    "sayit": {
        "en": "sayit",
        "de": "Sayit",
        "ru": "sayit",
        "pt": "sayit",
        "nl": "Sayit",
        "fr": "sayit",
        "it": "sayit",
        "es": "sayit",
        "pl": "sayit",
        "zh-cn": "sayit"
    },
    "close": {
        "en": "close",
        "de": "schließen",
        "ru": "Закрыть",
        "pt": "perto",
        "nl": "dichtbij",
        "fr": "proche",
        "it": "chiudere",
        "es": "Cerrar",
        "pl": "blisko",
        "zh-cn": "关闭"
    },
    "check": {
        "en": "check",
        "de": "Prüfen",
        "ru": "проверить",
        "pt": "verificação",
        "nl": "controle check check check",
        "fr": "contrôle",
        "it": "verifica",
        "es": "cheque",
        "pl": "check",
        "zh-cn": "检查"
    },
    "error found in": {
        "en": "error found in",
        "de": "Fehlerhafte Eigabe erkannt",
        "ru": "ошибка найдена в",
        "pt": "erro encontrado em",
        "nl": "error gevonden in",
        "fr": "erreur trouvée dans",
        "it": "errore trovato in",
        "es": "error encontrado en",
        "pl": "błąd znaleziony w błędzie",
        "zh-cn": "错误发现"
    },
    "Error found in configuration": {
        "en": "Error found in configuration",
        "de": "Fehlerhafte Konfiguration erkannt",
        "ru": "Ошибка найдена в конфигурации",
        "pt": "Erro encontrado na configuração",
        "nl": "Error gevonden in vertrouwen",
        "fr": "Erreur trouvée dans la configuration",
        "it": "Errore trovato nella configurazione",
        "es": "Error encontrado en la configuración",
        "pl": "Error znalazł się w konfiguracji",
        "zh-cn": "组合中发现的票据"
    },
    "username": {
        "en": "username",
        "de": "Username",
        "ru": "имя пользователя",
        "pt": "nome de utilizador",
        "nl": "gebruikersnaam",
        "fr": "username",
        "it": "nome utente",
        "es": "nombre de usuario",
        "pl": "username",
        "zh-cn": "用户名称"
    },
    "instance": {
        "en": "Instance",
        "de": "Instanz",
        "ru": "Экземпляр",
        "pt": "Instância",
        "nl": "Instantie:",
        "fr": "Instance",
        "it": "Istanza",
        "es": "Instance",
        "pl": "Instancja",
        "zh-cn": "实例"
    },
    "priority": {
        "en": "priority",
        "de": "Priorität",
        "ru": "приоритет",
        "pt": "prioridade",
        "nl": "prioriteit",
        "fr": "priorité",
        "it": "priorità",
        "es": "prioridad",
        "pl": "priorytet priorytetowy",
        "zh-cn": "优先重点"
    },
    "sound": {
        "en": "sound",
        "de": "Ton",
        "ru": "звук",
        "pt": "som",
        "nl": "klinkt goed",
        "fr": "sonore",
        "it": "suono",
        "es": "sonido",
        "pl": "dźwięk",
        "zh-cn": "健全"
    }

};