/global systemDictionary:true /
"use strict";

// @ts-ignore
systemDictionary = {
    "Monitoring of devices based on consumption": {
        "en": "Monitoring of devices based on consumption",
        "de": "Überwachung von Geräten anhand des Verbrauchs",
        "ru": "Мониторинг устройств на основе потребления",
        "pt": "Monitoramento de dispositivos com base no consumo",
        "nl": "Toezicht op apparaten op basis van verbruik",
        "fr": "Suivi des appareils en fonction de la consommation",
        "it": "Monitoraggio dei dispositivi in base ai consumi",
        "es": "Monitorización de dispositivos en función del consumo",
        "pl": "Monitoring urządzeń na podstawie zużycia",
        "zh-cn": "基于消耗的设备监控"
    },
    "Configuration": {
        "en": "Configuration",
        "de": "Konfiguration",
        "ru": "Конфигурация",
        "pt": "Configuração",
        "nl": "Configuratie",
        "fr": "Configuration",
        "it": "Configurazione",
        "es": "Configuración",
        "pl": "Konfiguracja",
        "zh-cn": "配置"
    },
    "active": {
        "en": "active",
        "de": "aktiv",
        "ru": "активный",
        "pt": "ativo",
        "nl": "actief",
        "fr": "actif",
        "it": "attivo",
        "es": "activo",
        "pl": "aktywny",
        "zh-cn": "积极的"
    },
    "add": {
        "en": "add",
        "de": "hinzufügen",
        "ru": "добавить",
        "pt": "adicionar",
        "nl": "_",
        "fr": "ajouter",
        "it": "aggiungere",
        "es": "añadir",
        "pl": "dodać",
        "zh-cn": "增 编"
    },
    "linkedDevice": {
        "en": "Linked devices",
        "de": "Verknüpfte Geräte",
        "ru": "Связанные устройства",
        "pt": "Dispositivos ligados",
        "nl": "Vertaling:",
        "fr": "Appareils connectés",
        "it": "Dispositivi collegati",
        "es": "Dispositivos vinculados",
        "pl": "Urządzenia linkujące",
        "zh-cn": "联系装置"
    },
    "measuringDevice": {
        "en": "Measuring device / socket",
        "de": "Messgerät / Steckdose",
        "ru": "Измерительное устройство / розетка",
        "pt": "Dispositivo de medição / soquete",
        "nl": "Vermenigvuldigen apparaat / socket",
        "fr": "Appareil de mesure / prise",
        "it": "Dispositivo di misura / presa",
        "es": "Dispositivo de medición / toma",
        "pl": "Measuring device / gniazdo",
        "zh-cn": "测量装置/装置"
    },
    "device": {
        "en": "device",
        "de": "Gerät",
        "ru": "устройство",
        "pt": "dispositivo",
        "nl": "apparaat",
        "fr": "appareil",
        "it": "dispositivo",
        "es": "dispositivo",
        "pl": "urządzenie",
        "zh-cn": "设备"
    },
    "switch off": {
        "en": "switch off",
        "de": "ausschalten",
        "ru": "выключить",
        "pt": "desligar",
        "nl": "Uitzetten",
        "fr": "éteindre",
        "it": "spegnere",
        "es": "apagar",
        "pl": "wyłączyć",
        "zh-cn": "关掉"
    },
    "switch off after minutes": {
        "en": "switch off after minutes",
        "de": "Abschalten nach Minuten",
        "ru": "выключить через несколько минут",
        "pt": "desligue após minutos",
        "nl": "na minuten uitschakelen",
        "fr": "s'éteint après quelques minutes",
        "it": "si spegne dopo pochi minuti",
        "es": "apagar después de minutos",
        "pl": "wyłącz po minutach",
        "zh-cn": "几分钟后关闭"
    },
    "abort detection": {
        "en": "abort detection",
        "de": "Abbrucherkennung",
        "ru": "прервать обнаружение",
        "pt": "detecção de aborto",
        "nl": "detectie afbreken",
        "fr": "abandonner la détection",
        "it": "interruzione del rilevamento",
        "es": "abortar la detección",
        "pl": "przerwać wykrywanie",
        "zh-cn": "中止检测"
    },
    "devices": {
        "en": "devices",
        "de": "Geräte",
        "ru": "устройства",
        "pt": "dispositivos",
        "nl": "apparaten",
        "fr": "dispositifs",
        "it": "dispositivi",
        "es": "dispositivos",
        "pl": "urządzenia",
        "zh-cn": "设备"
    },
    "Input checked": {
        "en": "Input checked",
        "de": "Eingabe überprüft",
        "ru": "Ввод проверен",
        "pt": "Entrada verificada",
        "nl": "Invoer aangevinkt",
        "fr": "Entrée cochée",
        "it": "Input controllato",
        "es": "Entrada marcada",
        "pl": "Wejście sprawdzone",
        "zh-cn": "输入检查"
    },
    "help": {
        "en": "help",
        "de": "Hilfe",
        "ru": "помощь",
        "pt": "ajuda",
        "nl": "helpen",
        "fr": "aider",
        "it": "aiuto",
        "es": "ayudar",
        "pl": "Wsparcie",
        "zh-cn": "帮助"
    },
    "Required fields": {
        "en": "Required fields",
        "de": "Felder erforderlich",
        "ru": "Обязательные поля",
        "pt": "Os campos obrigatórios",
        "nl": "Verplichte velden",
        "fr": "Champs obligatoires",
        "it": "Campi richiesti",
        "es": "Campos requeridos",
        "pl": "Wymagane pola",
        "zh-cn": "必填字段"
    },
    "device name": {
        "en": "device name",
        "de": "Gerätename",
        "ru": "имя устройства",
        "pt": "nome do dispositivo",
        "nl": "toestelnaam",
        "fr": "nom de l'appareil",
        "it": "nome del dispositivo",
        "es": "nombre del dispositivo",
        "pl": "Nazwa urządzenia",
        "zh-cn": "设备名称"
    },
    "device type": {
        "en": "device type",
        "de": "Gerätetyp",
        "ru": "тип устройства",
        "pt": "tipo de dispositivo",
        "nl": "soort apparaat",
        "fr": "type d'appareil",
        "it": "tipo di dispositivo",
        "es": "tipo de dispositivo",
        "pl": "rodzaj urządzenia",
        "zh-cn": "设备类型",
    },
    "consumption": {
        "en": "consumption",
        "de": "Verbrauch",
        "ru": "потребление",
        "pt": "consumo",
        "nl": "consumptie",
        "fr": "consommation",
        "it": "consumo",
        "es": "consumo",
        "pl": "konsumpcja",
        "zh-cn": "消耗"
    },
    "Power switch": {
        "en": "Power switch",
        "de": "Stromschalter",
        "ru": "Выключатель",
        "pt": "Interruptor de energia",
        "nl": "Aan/uit-schakelaar:",
        "fr": "Interrupteur",
        "it": "Interruttore di alimentazione",
        "es": "Interruptor de alimentación",
        "pl": "Włącznik zasilania",
        "zh-cn": "开关;电源开关"
    },
    "starttext": {
        "en": "starttext",
        "de": "Starttext",
        "ru": "стартовый текст",
        "pt": "texto inicial",
        "nl": "starttekst",
        "fr": "texte de début",
        "it": "testo iniziale",
        "es": "texto de inicio",
        "pl": "tekst startowy",
        "zh-cn": "开始文本"
    },
    "endtext": {
        "en": "endtext",
        "de": "Endtext",
        "ru": "конечный текст",
        "pt": "texto final",
        "nl": "eindtekst",
        "fr": "texte de fin",
        "it": "testo finale",
        "es": "texto final",
        "pl": "tekst końcowy",
        "zh-cn": "正文"
    },
    "delete": {
        "en": "delete",
        "de": "löschen",
        "ru": "удалять",
        "pt": "excluir",
        "nl": "verwijderen",
        "fr": "effacer",
        "it": "eliminare",
        "es": "Eliminar",
        "pl": "usunąć",
        "zh-cn": "删除"
    },
    "Pls check input": {
        "en": "Pls check input",
        "de": "Bitte Eingabe prüfen",
        "ru": "Пожалуйста, проверьте ввод",
        "pt": "Por favor, verifique a entrada",
        "nl": "Pls check input",
        "fr": "Veuillez vérifier l'entrée",
        "it": "Si prega di controllare l'input",
        "es": "Por favor verifique la entrada",
        "pl": "Pls sprawdź wejście!",
        "zh-cn": "请检查输入"
    },
    "invalid input detected": {
        "en": "invalid input detected",
        "de": "Ungültige Eingabe erkannt",
        "ru": "обнаружен неверный ввод",
        "pt": "entrada inválida detectada",
        "nl": "ongeldige invoer gedetecteerd",
        "fr": "entrée invalide détectée",
        "it": "è stato rilevato un input non valido",
        "es": "entrada no válida detectada",
        "pl": "wykryto nieprawidłowe dane wejściowe",
        "zh-cn": "检测到无效输入"
    },
    "volume 0-100": {
        "en": "volume 0-100",
        "de": "Lautstärke 0-100",
        "ru": "громкость 0-100",
        "pt": "volume 0-100",
        "nl": "volume 0-100",
        "fr": "volume 0-100",
        "it": "volume 0-100",
        "es": "volumen 0-100",
        "pl": "objętość 0-100",
        "zh-cn": "音量 0-100"
    },
    "active from hour": {
        "en": "active from hour",
        "de": "aktiv ab stunde",
        "ru": "активный с часа",
        "pt": "ativo de hora",
        "nl": "quality over quantity (qoq) releases vertaling:",
        "fr": "active à partir de l ' heure",
        "it": "attivo da ora",
        "es": "activo desde la hora",
        "pl": "aktywnie od godziny",
        "uk": "активний час",
        "zh-cn": "积极时间"
      },
      "active from minute": {
        "en": "active from minute",
        "de": "aktiv ab minute",
        "ru": "активный с минуты",
        "pt": "ativo de minuto",
        "nl": "actief",
        "fr": "active à partir de la minute",
        "it": "attivo dal minuto",
        "es": "activo desde el minuto",
        "pl": "aktywnie",
        "uk": "активний з хвилини",
        "zh-cn": "引言"
      },
      "inactive from hour" : {
        "en": "inactive from hour",
        "de": "inaktiv von stunde",
        "ru": "неактивный от часа",
        "pt": "inativo de hora",
        "nl": "inactief van uur",
        "fr": "inactif à partir de l ' heure",
        "it": "inattivo da ora",
        "es": "inactivo desde la hora",
        "pl": "nieaktywny od godziny",
        "uk": "неактивний час",
        "zh-cn": "b. 小时内的活动"
      },
      "inactive from minute" : {
        "en": "inactive from minute",
        "de": "inaktiv von minute",
        "ru": "неактивно с минуты",
        "pt": "inativo de minuto",
        "nl": "inactief van minuut",
        "fr": "inactif de la minute",
        "it": "inattivo da minuto",
        "es": "inactivo desde el minuto",
        "pl": "nieaktywny od minuty",
        "uk": "неактивний від хвилини",
        "zh-cn": "导 言"
      },
    "no entries found": {
        "en": "no entries found",
        "de": "Keine Einträge gefunden",
        "ru": "записей не найдено",
        "pt": "nenhuma entrada encontrada",
        "nl": "geen inzendingen gevonden",
        "fr": "aucune entrée trouvée",
        "it": "nessuna voce trovata",
        "es": "entradas no encontradas",
        "pl": "nie znaleziono wpisów",
        "zh-cn": "未找到条目"
    },
    "pushover instance": {
        "en": "pushover instance",
        "de": "Pushover-Instanz",
        "ru": " пуш-овер экземпляр",
        "pt": "instância de pushover",
        "nl": "pushover-instantie",
        "fr": "instance de transfert",
        "it": "istanza pushover",
        "es": "instancia pushover",
        "pl": "instancja pushover",
        "zh-cn": "推送实例"
    },
    "priority": {
        "en": "priority",
        "de": "Priorität",
        "ru": " приоритет",
        "pt": "prioridade",
        "nl": "prioriteit",
        "fr": "priorité",
        "it": "priorità",
        "es": "prioridad",
        "pl": "priorytet",
        "zh-cn": "优先事项"
    },
    "sound": {
        "en": "sound",
        "de": "Klang",
        "ru": "звук",
        "pt": "som",
        "nl": "geluid",
        "fr": "son",
        "it": "suono",
        "es": "sonar",
        "pl": "dźwięk",
        "zh-cn": "声音"
    },
    "name": {
        "en": "name",
        "de": "Name",
        "ru": "название",
        "pt": "nome",
        "nl": "naam",
        "fr": "Nom",
        "it": "nome",
        "es": "nombre",
        "pl": "nazwać",
        "zh-cn": "姓名"
    },
    "sender address": {
        "en": "sender address",
        "de": "Absenderadresse",
        "ru": "адрес отправителя",
        "pt": "Endereço do remetente",
        "nl": "Zender adres",
        "fr": "adresse de l'expéditeur",
        "it": "indirizzo del mittente",
        "es": "dirección del remitente",
        "pl": "adres nadawcy",
        "zh-cn": "发件人地址"
    },
    "receiver address": {
        "en": "receiver address",
        "de": "Empfängeradresse",
        "ru": "адрес получателя",
        "pt": "endereço do destinatário",
        "nl": "ontvanger adres",
        "fr": "adresse du destinataire",
        "it": "indirizzo del destinatario",
        "es": "dirección del destinatario",
        "pl": "Odbiorca adres",
        "zh-cn": "收件人地址"
    },
    "deviceValues": {
        "en": "Device values",
        "de": "Gerätewerte",
        "ru": "Значения устройства",
        "pt": "Valores de dispositivo",
        "nl": "Devicewaarden",
        "fr": "Valeurs du dispositif",
        "it": "Valori del dispositivo",
        "es": "Valores de dispositivo",
        "pl": "Wartości dyskretnych",
        "zh-cn": "丧失价值观"
    },
    "threshold start (watt)": {
        "en": "threshold start (watt)",
        "de": "Schwelle Start (Watt)",
        "ru": "порог «старт» (ватт)",
        "pt": "limite iniciar (watt)",
        "nl": "drempel start (watt)",
        "fr": "seuil start (watt)",
        "it": "soglia start (watt)",
        "es": "umbral inicio (vatios)",
        "pl": "próg „start” (wat)",
        "zh-cn": "阈值“开始”（瓦特）"
    },
    "threshold end (watt)": {
        "en": "threshold end (watt)",
        "de": "Schwelle Ende (Watt)",
        "ru": "порог «конец» (ватт)",
        "pt": "limite fim (watt)",
        "nl": "drempel eind (watt)",
        "fr": "seuil fin (watt)",
        "it": "soglia fine (watt)",
        "es": "umbral fin (vatios)",
        "pl": "próg „koniec” (wat)",
        "zh-cn": "阈值“结束”（瓦特）"
    },
    "threshold standby (watt)": {
        "en": "threshold standby (watt)",
        "de": "Schwelle Standby (Watt)",
        "ru": "порог «ожидания» (ватт)",
        "pt": "limiar standby (watt)",
        "nl": "drempel standby (watt)",
        "fr": "seuil veille (watt)",
        "it": "soglia standby (watt)",
        "es": "umbral en espera (vatios)",
        "pl": "próg czuwania (wat)",
        "zh-cn": "阈值“待机”（瓦特）"
    },
    "number of start values": {
        "en": "number of start values",
        "de": "Anzahl der Start-Werte",
        "ru": "количество «начальных» значений",
        "pt": "número de valores iniciais",
        "nl": "aantal start-waarden",
        "fr": "nombre de valeurs début",
        "it": "numero di valori iniziali",
        "es": "número de valores de inicio",
        "pl": "liczba wartości „początkowych”",
        "zh-cn": "“开始”值的数量"
    },
    "number of end values": {
        "en": "number of ​end values",
        "de": "Anzahl der ​End-Werte",
        "ru": "количество «конечных» значений",
        "pt": "número de valores final",
        "nl": "aantal ​eind-waarden",
        "fr": "nombre de valeurs fin",
        "it": "numero di valori finali.",
        "es": "número de valores finales",
        "pl": "liczba ​wartości końcowych",
        "zh-cn": "“结束”值的数量"
    },
    "status: in action": {
        "en": "status: in action",
        "de": "Status: in Aktion ",
        "ru": "статус: 'в действии « »",
        "pt": "status: 'em ação '",
        "nl": "in actie '",
        "fr": "statut: 'en action '",
        "it": "stato: 'in azione '",
        "es": "status: 'in action '",
        "pl": "status: „w działaniu”. '",
        "uk": "статус: 'в дії р",
        "zh-cn": "现状:行动 评 注"
      },
      "status: standby": {
        "en": "status: standby",
        "de": "Status: Standby",
        "ru": "статус: standby",
        "pt": "status: standby",
        "nl": "stand-by",
        "fr": "statut: standby",
        "it": "stato: standby",
        "es": "status: standby",
        "pl": "status:",
        "uk": "статус: очікування",
        "zh-cn": "现状:待命状态"
      },
      "status: device off": {
        "en": "status: device off",
        "de": "Status: ausgeschaltet ",
        "ru": "статус: 'device off « »",
        "pt": "status: 'dispositivo off '",
        "nl": "vernietiging '",
        "fr": "statut: 'device off '",
        "it": "stato: '",
        "es": "status: 'device off '",
        "pl": "statystyka: „odc. '",
        "uk": "статус: 'розвиток від р",
        "zh-cn": "地位:退出 评 注"
      },
    "standby": {
        "en": "standby",
        "de": "Standby",
        "ru": "«ожидание»",
        "pt": "em espera",
        "nl": "stand-by",
        "fr": "en attente",
        "it": "standby",
        "es": "en espera",
        "pl": "„gotowość”",
        "zh-cn": "状态：“待命”"
    },
    "device off": {
        "en": "device off",
        "de": "Gerät aus",
        "ru": "устройство выключено",
        "pt": "dispositivo desligado",
        "nl": "apparaat uit",
        "fr": "appareil éteint",
        "it": "dispositivo spento",
        "es": "dispositivo apagado",
        "pl": "„urządzenie wyłączone”",
        "zh-cn": "状态：“设备关闭”"
    },
    "device status": {
        "en": "Device status",
        "de": "Gerätestatus",
        "ru": "Статус устройства",
        "pt": "Status do dispositivo",
        "nl": "Device status",
        "fr": "Statut du dispositif",
        "it": "Stato del dispositivo",
        "es": "Estado del dispositivo",
        "pl": "Status Device",
        "zh-cn": "丧失地位"
    },
    "custom device types": {
        "en": "custom device types",
        "de": "benutzerdefinierte Gerätetypen",
        "ru": "пользовательские типы устройств",
        "pt": "tipos de dispositivo personalizados",
        "nl": "gebruikelijke apparaten",
        "fr": "types de périphériques personnalisés",
        "it": "tipi di dispositivo personalizzati",
        "es": "tipos de dispositivo personalizados",
        "pl": "typ maszynowy",
        "uk": "типи користувацького пристрою",
        "zh-cn": "习惯装置"
      },
      "default device types": {
        "en": "default device types",
        "de": "Standardgerätetypen",
        "ru": "типы устройств по умолчанию",
        "pt": "tipos de dispositivo padrão",
        "nl": "defecte apparatuur types",
        "fr": "types de périphériques par défaut",
        "it": "tipi di dispositivo di default",
        "es": "tipos de dispositivo predeterminados",
        "pl": "typename",
        "uk": "типи пристроїв за замовчуванням",
        "zh-cn": "过期装置"
      },
      "add device": {
        "en": "add device",
        "de": "Gerät hinzufügen",
        "ru": "добавить устройство",
        "pt": "adicionar dispositivo",
        "nl": "voeg",
        "fr": "ajouter le dispositif",
        "it": "aggiungere dispositivo",
        "es": "añadir dispositivo",
        "pl": "dodać",
        "uk": "додати пристрій",
        "zh-cn": "增加装置"
      },
    "telegram user": {
        "en": "telegram user",
        "de": "Telegrambenutzer",
        "ru": "пользователь телеграммы",
        "pt": "usuário de telegrama",
        "nl": "telegram gebruiker",
        "fr": "utilisateur de télégramme",
        "it": "utente del telegramma",
        "es": "usuario de telegramas",
        "pl": "użytkownik telegramu",
        "zh-cn": "电报用户"
    },
    "telegram": {
        "en": "telegram",
        "de": "Telegram",
        "ru": "telegram",
        "pt": "telegram",
        "nl": "telegram",
        "fr": "telegram",
        "it": "telegram",
        "es": "telegram",
        "pl": "telegram",
        "zh-cn": "telegram"
    },
    "signal": {
        "en": "Signal-cmb",
        "de": "Signal-cmb",
        "ru": "Signal-cmb",
        "pt": "Signal-cmb",
        "nl": "Signal-cmb",
        "fr": "Signal-cmb",
        "it": "Signal-cmb",
        "es": "Signal-cmb",
        "pl": "Signal-cmb",
        "zh-cn": "Signal-cmb"
    },
    "phone": {
        "en": "phone",
        "de": "Telefon",
        "ru": "телефон",
        "pt": "telefone",
        "nl": "telefoon telefoon telefoon",
        "fr": "téléphone",
        "it": "telefono",
        "es": "teléfono",
        "pl": "telefon",
        "zh-cn": "电话"
    },
    "whatsapp user": {
        "en": "whatsapp user",
        "de": "WhatsApp-Benutzer",
        "ru": "пользователь WhatsApp",
        "pt": "usuário whatsapp",
        "nl": "whatsapp-gebruiker",
        "fr": "utilisateur WhatsApp",
        "it": "utente whatsapp",
        "es": "usuario de whatsapp",
        "pl": "użytkownik WhatsApp",
        "zh-cn": "whatsapp用户"
    },
    "whatsapp": {
        "en": "whatsapp-cmb",
        "de": "WhatsApp-cmb",
        "ru": "WhatsApp-cmb",
        "pt": "Whatsapp-cmb",
        "nl": "whatsapp-cmb",
        "fr": "WhatsApp-cmb",
        "it": "WhatsApp-cmb",
        "es": "whatsapp-cmb",
        "pl": "whatsapp-cmb",
        "zh-cn": "whatsapp-cmb"
    },
    "alexa": {
        "en": "alexa",
        "de": "Alexa",
        "ru": "alexa",
        "pt": "alexa",
        "nl": "alexa",
        "fr": "alexa",
        "it": "alexa",
        "es": "alexa",
        "pl": "alexa",
        "zh-cn": "alexa"
    },
    "pushover user": {
        "en": "pushover user",
        "de": "Pushover-Benutzer",
        "ru": "слабый пользователь",
        "pt": "usuário simples",
        "nl": "pushover gebruiker",
        "fr": "utilisateur pushover",
        "it": "utente pushover",
        "es": "usuario pushover",
        "pl": "użytkownik pushover",
        "zh-cn": "推倒用户"
    },
    "pushover": {
        "en": "pushover",
        "de": "Pushover",
        "ru": "pushover",
        "pt": "pushover",
        "nl": "pushover",
        "fr": "pushover",
        "it": "pushover",
        "es": "pushover",
        "pl": "pushover",
        "zh-cn": "pushover"
    },
    "title": {
        "en": "title",
        "de": "Betreff",
        "ru": "название",
        "pt": "título",
        "nl": "titel",
        "fr": "titre",
        "it": "titolo",
        "es": "título",
        "pl": "tytuł",
        "zh-cn": "标题"
    },
    "email account": {
        "en": "email account",
        "de": "Email-Konto",
        "ru": "адрес электронной почты",
        "pt": "conta de e-mail",
        "nl": "email account",
        "fr": "compte email",
        "it": "account email",
        "es": "cuenta de correo electrónico",
        "pl": "Konto e-mail",
        "zh-cn": "电子邮件帐户"
    },
    "email": {
        "en": "email",
        "de": "Email",
        "ru": "Эл. адрес",
        "pt": "o email",
        "nl": "e-mail",
        "fr": "e-mail",
        "it": "e-mail",
        "es": "Email",
        "pl": "e-mail",
        "zh-cn": "电子邮件"
    },
    "sayit device": {
        "en": "sayit device",
        "de": "Sayit-Gerät",
        "ru": "скажи устройство",
        "pt": "dispositivo sayit",
        "nl": "Sayit-apparaat",
        "fr": "dis-le dispositif",
        "it": "dispositivo di dirlo",
        "es": "dilo dispositivo",
        "pl": "powiedz urządzenie",
        "zh-cn": "sayit 设备"
    },
    "sayit": {
        "en": "sayit",
        "de": "Sayit",
        "ru": "sayit",
        "pt": "sayit",
        "nl": "Sayit",
        "fr": "sayit",
        "it": "sayit",
        "es": "sayit",
        "pl": "sayit",
        "zh-cn": "sayit"
    },
    "close": {
        "en": "close",
        "de": "schließen",
        "ru": "Закрыть",
        "pt": "perto",
        "nl": "dichtbij",
        "fr": "proche",
        "it": "chiudere",
        "es": "Cerrar",
        "pl": "blisko",
        "zh-cn": "关闭"
    },
    "check": {
        "en": "check",
        "de": "Prüfen",
        "ru": "проверить",
        "pt": "verificação",
        "nl": "controle check check check",
        "fr": "contrôle",
        "it": "verifica",
        "es": "cheque",
        "pl": "check",
        "zh-cn": "检查"
    },
    "error found in": {
        "en": "error found in",
        "de": "Fehlerhafte Eigabe erkannt",
        "ru": "ошибка найдена в",
        "pt": "erro encontrado em",
        "nl": "error gevonden in",
        "fr": "erreur trouvée dans",
        "it": "errore trovato in",
        "es": "error encontrado en",
        "pl": "błąd znaleziony w błędzie",
        "zh-cn": "错误发现"
    },
    "Error found in configuration": {
        "en": "Error found in configuration",
        "de": "Fehlerhafte Konfiguration erkannt",
        "ru": "Ошибка найдена в конфигурации",
        "pt": "Erro encontrado na configuração",
        "nl": "Error gevonden in vertrouwen",
        "fr": "Erreur trouvée dans la configuration",
        "it": "Errore trovato nella configurazione",
        "es": "Error encontrado en la configuración",
        "pl": "Error znalazł się w konfiguracji",
        "zh-cn": "组合中发现的票据"
    },
    "username": {
        "en": "username",
        "de": "Username",
        "ru": "имя пользователя",
        "pt": "nome de utilizador",
        "nl": "gebruikersnaam",
        "fr": "username",
        "it": "nome utente",
        "es": "nombre de usuario",
        "pl": "username",
        "zh-cn": "用户名称"
    },
    "instance": {
        "en": "Instance",
        "de": "Instanz",
        "ru": "Экземпляр",
        "pt": "Instância",
        "nl": "Instantie:",
        "fr": "Instance",
        "it": "Istanza",
        "es": "Instance",
        "pl": "Instancja",
        "zh-cn": "实例"
    },
    "Edit": {
        "en": "Edit",
        "de": "Bearbeiten",
        "ru": "Редактировать",
        "pt": "Editar",
        "nl": "Ed",
        "fr": "Edit",
        "it": "Modifica",
        "es": "Editar",
        "pl": "Edyta",
        "uk": "Редагування",
        "zh-cn": "编辑"
      },
      "custom type config": {
        "en": "custom type config",
        "de": "benutzerdefinierte Gerätetypen",
        "ru": "пользовательский тип config",
        "pt": "configuração de tipo personalizado",
        "nl": "- ja",
        "fr": "configuration personnalisée",
        "it": "tipo personalizzato configurazione",
        "es": "configuración de tipo personalizado",
        "pl": "konfiguracja",
        "uk": "налаштування користувацького типу",
        "zh-cn": "习俗类型"
      },
      "default type config": {
        "en": "default type config",
        "de": "Standardgerätetypen",
        "ru": "тип по умолчанию config",
        "pt": "default type config",
        "nl": "defecte type configuur",
        "fr": "default type config",
        "it": "predefinito type config",
        "es": "configuración tipo predeterminado",
        "pl": "typename",
        "uk": "налаштування типу за замовчуванням",
        "zh-cn": "违约情况"
      },
};